### ISSUE TITLE
Participate in hacktoberfest?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#127]
Each year the Mozilla community runs a month-long event called [Hacktoberfest](https://hacktoberfest.digitalocean.com/) that encourages broader participation and PRs in open source projects. The basic idea is that OS projects add a "hacktoberfest" label to issues and this makes them discoverable on the Hacktoberfest platform (they have things like leaderboards etc).

Shall we use this as an opportunity to generate some interest and PRs in any of our projects? What do folks think? [Some general instructions are here](https://hacktoberfest.digitalocean.com/#maintainers)

**Comment by chrisjsewell** [comment]
Yeh sounds good to me 👍
