### ISSUE TITLE
Create a Jupyter Book badge

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#156]
In a recent comment from @chrisjsewell he showed off a page with some nice AIIDA badges. This got me thinking it could be cool to have a Jupyter Book badge that users can add to their site.

I very hastily put together this one, but welcome feedback/suggestions/etc:

![](https://img.shields.io/badge/read-jupyter%20book-orange?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA5CAYAAACMGIOFAAAACXBIWXMAAAWJAAAFiQFtaJ36AAADx0lEQVRoge1aS27bMBAdFlkKiHuCuCst654gygmqnsC+QZ2dls5Ou7gnsHKC+gZxTlBnqV18gtqA9lOMOwwI/iQrkpWqeoABW6LIeeRw5g1lgYjQd3zoPcOBZI8wkOwLBpJ9wX9B8qKsQZGEIwCIAWDMl7IgzV/aN81pz5jtIbvIjnWQ5nvfM17FUyQhdZYBwKV261uQ5uumDK+KIgknAPBLa34AgHmQ5pmrG6e7Fkk4A4CfFoKEWduEHJhbLpN9qyIJbfeOsJLkGVu1bHDTuC+SMLL16VpJ56yweyw7IrLk8V1Y2K67SMaWa88AcEsBKEjzTWNmn4AgzbccAMmOneXJa1tv1sBTJKEtGn3hQd4FOOr/rmJn5Tz5ngjCX3v27F06RvqFRsWAEGIhhED5cbSJhBAbtR39rjmkNz9KdKF4Fq690xa6IHl2EdE0SVIdN8rHACJSGvgIAA8Nj+1EqXY9BYj4wnrSC0TcCyHOpn9rkxRCUL6KFOHuwgsiOnWl0t+I5WKkRUhy74wmpq6tb1lJiohXFdo9sRv7MGEPsOlkClIUtWNErBWFjT3Jlce5cekgKEH3HoloBbsMz3pdSRblc4+k0xE72sqBpjUmasf6dMsuG2v9ZLRNSlx3xUI9k/LzggkSuXvPg0bYR8QtG2OAEn4NkjSRkUZgzUJBVkSXvBBSiGeOnEtjT4sk/BGk+Vy6q68+3J2p6ohtK8RB605tJ79woUx73oUjr/dyxvPE6ccF1ZM+n9q5JOmLflcl9eU5YJ0APr3wScTlK8kgzenHJ1YhtqLUWnE3iLJcqwY41T7bNjswj5sgzY979zW68gncjCPTo/Zg24L6SghBCd8wmkWHWvGX5UrjUMsQAxR2iyR8i8FeCCEmvAJ6+pkyobWSQiJuq+bQsiBouHaj2rUiaFW+Oppel3jNXR3V00V0tSVy3+GUvH+LiNaDqjK0tZLGEYQE7TshxFJrs+fPjHXsSLm+6VKg+6DuN2OPsFqyodZKlaFRklwu6Xqzk+NLFW+pJ2eWPKUHjcM/S5JDfdlrhAML7s7egElUjq58mHsEG247wZbYMcG2z2onVRqdspKLIgkX8l0gIo65pNKxb5scT/jcUWgbY7teE2w9av+BpVPtkF4XTG5hUUESuyDNDR3sclefdJq2FeorgCL3d89RibWaspKsUIxW2gstwFfcP7sWxxd4Yg/RrtKCq+49Hp24tpAz8PADERemc96jB64SunoJu2YvirmYf+Y/Rni3z/BX0L5gINkXDCT7goFkXzCQ7AUA4A+HLUQOgF33SgAAAABJRU5ErkJggg==&style=flat)

or

![](https://img.shields.io/badge/jupyter-book-orange?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADkAAAA5CAYAAACMGIOFAAAACXBIWXMAAAWJAAAFiQFtaJ36AAADx0lEQVRoge1aS27bMBAdFlkKiHuCuCst654gygmqnsC+QZ2dls5Ou7gnsHKC+gZxTlBnqV18gtqA9lOMOwwI/iQrkpWqeoABW6LIeeRw5g1lgYjQd3zoPcOBZI8wkOwLBpJ9wX9B8qKsQZGEIwCIAWDMl7IgzV/aN81pz5jtIbvIjnWQ5nvfM17FUyQhdZYBwKV261uQ5uumDK+KIgknAPBLa34AgHmQ5pmrG6e7Fkk4A4CfFoKEWduEHJhbLpN9qyIJbfeOsJLkGVu1bHDTuC+SMLL16VpJ56yweyw7IrLk8V1Y2K67SMaWa88AcEsBKEjzTWNmn4AgzbccAMmOneXJa1tv1sBTJKEtGn3hQd4FOOr/rmJn5Tz5ngjCX3v27F06RvqFRsWAEGIhhED5cbSJhBAbtR39rjmkNz9KdKF4Fq690xa6IHl2EdE0SVIdN8rHACJSGvgIAA8Nj+1EqXY9BYj4wnrSC0TcCyHOpn9rkxRCUL6KFOHuwgsiOnWl0t+I5WKkRUhy74wmpq6tb1lJiohXFdo9sRv7MGEPsOlkClIUtWNErBWFjT3Jlce5cekgKEH3HoloBbsMz3pdSRblc4+k0xE72sqBpjUmasf6dMsuG2v9ZLRNSlx3xUI9k/LzggkSuXvPg0bYR8QtG2OAEn4NkjSRkUZgzUJBVkSXvBBSiGeOnEtjT4sk/BGk+Vy6q68+3J2p6ohtK8RB605tJ79woUx73oUjr/dyxvPE6ccF1ZM+n9q5JOmLflcl9eU5YJ0APr3wScTlK8kgzenHJ1YhtqLUWnE3iLJcqwY41T7bNjswj5sgzY979zW68gncjCPTo/Zg24L6SghBCd8wmkWHWvGX5UrjUMsQAxR2iyR8i8FeCCEmvAJ6+pkyobWSQiJuq+bQsiBouHaj2rUiaFW+Oppel3jNXR3V00V0tSVy3+GUvH+LiNaDqjK0tZLGEYQE7TshxFJrs+fPjHXsSLm+6VKg+6DuN2OPsFqyodZKlaFRklwu6Xqzk+NLFW+pJ2eWPKUHjcM/S5JDfdlrhAML7s7egElUjq58mHsEG247wZbYMcG2z2onVRqdspKLIgkX8l0gIo65pNKxb5scT/jcUWgbY7teE2w9av+BpVPtkF4XTG5hUUESuyDNDR3sclefdJq2FeorgCL3d89RibWaspKsUIxW2gstwFfcP7sWxxd4Yg/RrtKCq+49Hp24tpAz8PADERemc96jB64SunoJu2YvirmYf+Y/Rni3z/BX0L5gINkXDCT7goFkXzCQ7AUA4A+HLUQOgF33SgAAAABJRU5ErkJggg==&style=flat)

a few thoughts:

- We should have a square logo that's easier to see (maybe a white background or white lettering)
- Colors should be jupyter orange
- Not sure about the wording "read | Jupyter Book" etc

edit: here's one with white text in the logo:

![](https://img.shields.io/badge/jupyter-book-orange?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACgAAAAbCAYAAAAOEM1uAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAZRSURBVFhHtVh9bFNVFL/3vbZr99qu25hbAAeYDYkOFv7QaBSJgoLiB0QQYiT+I4licJGJLn7NipgFN4hRgpkSTYj+4UAUUSEaCwSRxEAEJhkrQRBxVLrPdmu7vfeuv3P79rqByzasv+TsnnPveX2/d+455743zq5Ad82MQmHoy1SuPGgykady9qHmnvgZDx7QLZesIFpb5ncm1GrOzfmM8T8MIZoCnv5vefB80nKRGEbQXFOWE/fw3ZiexzlTaU4IdlYVfI72zum/pFOWEKspn4/f/pIzrpENPckE+8iX21rFg8yUToBijUwsY2rMwzdzzu8bJEeAfilXdSUsM2vgitrBBI9bJt3HzbhY3ZsqX0lmenYIwb7y8hKF8UWWyYQpTuKCNSlhLmd1J7us6axBC7ccR/Tu5YK9gXu10xyCo5iCrTCfn+yWToBNMKmbAQyetIXtZvwDX134/Qkbz/yJxxHWNKutrVVisVhxb2/vZCFEnjUtAZtHIpESWoNMDIVCDmvpKvAmZvg2nj6peVrXgwXSyoLg+dzlcllWhqCLORBAYYdWmGbKUocBBDXTNHdCjvX19a21piVAvMbtdh+nNcMw9ldWVk6ylkZGEA8vWJ9lUSh4V9K4eovHio6ODuyETGyfruv2VhAQwSTWejDmYyxUFMXO5WvFuAkWFhbGEKF5UKckk8n16dk0/H7/e1hbCDVrFT8mgl1dXQXxeHwhZBFy6wGHw3E7InSLpmlzYd+KiMnfwZyOqHVDlW0CugvXLOju7l7X09PzMsYnotHo6Ns+BCMSVJR0YVDi40bbMX6B6Oz4F3k1HA475UVDAH8v5DvILhCvw9R6jNuQ/weQq/dgfkzBsZ1MpvvAJVM9qtJLI35UQD6Fugc/undQMHcMcy7orrKyMnIdBqy78GBT8QC/Q6+DUDocgkzDNTsQ0fulI4GzAUujqPjyHKrNg8dfKq9EF38N9XsHzGKUD8cP6NxQZ/saWprJCTZV1bAooYIXoFJ3QA15vd5HQEZWPW48AcMvIDQV1x2B3+Li4uLLtHbhwoWcgoKCt0C6CmYokUgswVo89uKNj6OUt6NZK+BicmGewxPu46bzTQVV/TqMR9E0S4gc/RD+fOitb/mNdAJuRlHsHyqo4NHOZmodL5SUlETgb5KUlpYm8FCN0Ilwhc/nKyBHbaB3F8JwkHQiify6AcozQtGfBUHWD7EbcRr8OvbY+Cv8CqQQwb8t3QYqPYJ5Iu8FUbmV7Q7NgahIsoOgSBrM1BWUQC1CugEMj2BSEsWfJV1TymdKz2sESHhVVb3NMm2gQG4GsQJIBNGUee7ixlLs4CzScZ0OHnsEFzWKrmxR8upaWr2eM7Wmzp7DsjxzKcwOhU8nfTxob2+/Hvm1FDen6DihbwWhKszPRG7eBFkCt20gQUfkj2hTUboOvpKchVNcHXhqkzvc4N/UGk33L7zeqCrHKcAM6QKYzJSvQeMBIvY2ZCtUKhS6sQYym51O588wj0B2wqYH/xprtZAB7BbHlmUKUPCk3memgtYr14h5hgQYdw7m5OQEsW31ULcSMZBdjpEqPQyhdnMQ8jSqfgWkja4ZDf+lEChKKraRqlo+rcfjORMIBNahOlejGNbm5uZ+jnE52smcVCp1J0jNg92IljTm98sxEezs7JyK/JkDuQsyF8fXkyC1AUt0PW3diC0HfoJ6XVFRUQy6nUJjxagEm5ub6UT4GOoB3IBkP7btE9h0pm5HBLcQCfL9P5AhaCBfUduWhYTncq2ioqIfuUQE94HYD5DvQaoJshJbuQonA70cXDuoSrjIvNhSyQyBPDkIndXTp6kOcQj9aCLZON32MmHU+brzDvPGo/ZZmU20VRdruU7f3dj4BryRyLaGKIW8uuchpeGE7JF2BC96HRfB91fLpKdaiCMn1JPX09RWPWvcLWc0JF6ZPs2r+o9yoezOkJMBPMzrT9hv2DbBiuCpftXkq9DFz1pTFF6ucDbbr/blW1NZQ/8Am4EDvnTw/JfkhDikJwfq0Y/tbR5WJPTti179MPb3K+TaOVOIS/jK+qZ9ICm/urIJXTeaQeMn3CMCM4yjt9HsVRfnv3t+2BeknYNDQR/wCR+fwLnD0Xm56/KkxrbMR00W0Vk1JcDc7oDTUJOaVhS9+r8XjP0DXUDvb7DTKEUAAAAASUVORK5CYIL4C4URKXJ1UlLScZ/7YBCWYJxomiB2L0QbXgzAl8h1cz+m9VQEmp1oF3ZEjQYmwQitLsr6wbHRsMeFCIGgsgqC+iHlnQZfgQ2DLcfm4Rw1jzoiIzsOZ/bA10hyA2a62WbBCg7MAQjGFjrX59odxbkF8rdZKo45t9ZnpjtKsgvdyYr8LcxwXMSYeLHZMhwwJKa10rUuK0NTE6+iIujziel69S4TMwduvfw3FcUER/GYGQrTjkHZQCoyALGNtn6u0XxTg+EwZBph67ZrjZgeFeSawHQekcj4BnJjgtiVJ8++m7sVK385ZPyDQLGSoEHLaol7HyN5ktxgDAx8OdaX1NfXxytMBD07o1/4xw5b62o+9pUYCSpY/sJus8QXYloYfluV6HdPiANQKy8cE4Zi5HD+PUquH/S3A1Zhu2Vb1t1/aul1lFzrch4VcXwJlE6A2A6ctPfaKmqOxVKwRKzMi29Na32VcVGIPnlVzk/j3HgwteyifFv6Pz4Y+w8Xf1ymL5/srwAAAABJRU5ErkJggg==&style=flat)

**Comment by jstac** [comment]
Nice work.  I like the second one.

**Comment by mmcky** [comment]
@choldgraf I also like the second one. 
Just one comment I typically view badges as providing information about a status of some kind -- so the orange seems like it has a build error. Maybe i need to change my view of badges `:-)` as `jupyter orange` makes sense.
