### ISSUE TITLE
Discuss challenges with using Sphinx

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#16]
From a recent conversation with @stefanv, @rossbar, and others, I wanted to bring up a few criticisms that I have commonly heard about Sphinx, so that we can discuss how we can deal with them, and how much of a problem they'd be. I'd also be curious to hear what @chrisjsewell and @mmcky think about this.

# Sphinx is brittle and hard to debug

Something I have commonly heard is that Sphinx is too brittle, and often becomes a burden on the developer who has a hard time figuring out why something isn't working. E.g., error messages are hard to connect with changes that need to be made in the code, and diving into the Sphinx internals can quickly become a day's effort because of the complexity of Sphinx and because it is poorly-documented.

# Sphinx can be slow

I've also heard complaints that building sites with Sphinx can become extremely slow. For example, I believe that building the Matplotlib documentation took on the order of 8-10 minutes. Some of this is probably because of running code, examples, etc, but I wonder if we can run a profiler on Sphinx to see where the bottlenecks are. For example, if we added a step that converted documents into rST before going into Sphinx, would that significantly increase the build overhead? If we have a document with lots of cross-references, what does the function of added time look like (e.g. $O^N$ or $O(N)$)

# Docutils is difficult to debug and to contribute to

If the problem lies with Docutils, and not Sphinx, then a new set of challenges arise. Docutils is hosted on Sourceforge, and uses a mailing list for all conversations as well as code patches etc. This can make contributing upstream improvements tedious and time-consuming.

Those are the main ones that I can think of. I think the main question is whether these are insurmountable problems, or if they are problems that we can improve through upstream patches, or through engineering the backend in a way that avoids common pitfalls that users run into with Sphinx. It'd be great to hear what folks think.

**Comment by jlperla** [comment]
+1 for pandoc.  I find the sphinx toolchain to be very heavy, and it is a nightmare when it comes to transcoding.  As an example, we have had massive battles with sphinx putting `$` inside of a text block and literal code and having it come out escaped properly in Jupyter+HTML+latex output jointly.  This sort of things is already tested by the Rmd/Pandoc backend.  And if there are complementaries with the Rstudio crew in keeping pandoc up to date, so much the better.

**Comment by choldgraf** [comment]
I think it's worth discussing similar questions for Pandoc - it has its own set of pros and cons (to me, the biggest "con" being that it's written in Haskell and so it really is a black box to most in this community). Also I believe that, while RStudio has dependencies on Pandoc for RMarkdown etc, it is still largely [a one man show](https://github.com/jgm/pandoc/graphs/contributors)

I'm guessing that this tool stack will either use Pandoc or Sphinx as a document generation engine...I can see merits to both :-/

**Comment by chrisjsewell** [comment]
I think it's important to note here that pandoc is equivalent to docutils **not** sphinx, i.e. pandoc and docutils parse single documents to an output agnostic document AST (and have some associated writers), whereas sphinx is a framework around the single document parser, to handle a whole 'project'. If you want to use pandoc, you still need a *sphinx-type* framework around it.

**Comment by choldgraf** [comment]
Is it safe to say that the tools can be broken down like so?

|                    Step                    | Sphinx stack                | Bookdown stack |
|:------------------------------------------:|-----------------------------|----------------|
| Markup -> AST                              | docutils                    | pandoc         |
| cross refs and "publishing" features       | Sphinx                      | bookdown       |
| User-interface to facilitate and configure | ??? (Jupinx? Jupyter Book?) | bookdown       |

**Comment by jlperla** [comment]
I think that is a great way to describe it.  The HTML (and Latex/pdf) templating should also be considered as a major usability consideration.  I don't know the state of Jinja, but Hugo seems is a pretty safe bet these days.  An alternative, used by https://github.com/JunoLab/Weave.jl (effectively a subset of Rmd for python and julia) is http://mustache.github.io/  .  I think it is a bad idea to deviate from the bookdown stack, but just wanted to bring it up as an alternative direction people have taken for the same basic problem.

On that note, I can say with near certainty that if this project uses a Rmd based approach, the everyone in Julia would move towards using it and there would be contributors on tooling (e.g. https://atom.io/packages/language-weave and the vscode equivalent could move to using it).

**Comment by choldgraf** [comment]
Another quick thing - since we are talking about Sphinx being slow, I thought it'd be interesting to profile the creation of a Sphinx site. You can check out the repository that does this (and which you should be able to run pretty easily) here:

https://github.com/ExecutableBookProject/profile-sphinx-site

Here's the punchline:

https://github.com/ExecutableBookProject/profile-sphinx-site/blob/master/profile.svg

**Comment by chrisjsewell** [comment]
Interesting thanks @choldgraf, it would certainly be good to have this tool available to users in the workchain, particularly to assess any extensions that are causing a slow down (in this case obviously `autosummary`). I doubt there will be much difference between the base parsing speed of pandoc vs docutils though, and its certainly in docutils favour, that you have to spin up a subprocess every time you need to call pandoc.

To pick up on a few other points.

> Sphinx is brittle and hard to debug / Sphinx is slow

There is certainly improvements that can be made. But to some extent I guess it's the nature of the beast; it has to be quite complex to host all the features that it does, particularly allowing for extensibility. LaTeX for example is not always the simplest to use. I'll have to get round to actually trying out Bookdown.

I'd say the Sphinx documentation is pretty decent, if you fully read it. docutils, less so.

> If we have a document with lots of cross-references, what does the function of added time look like

I don't think it should make much difference, you just need one 'visitor' parse to collect the reference targets, and a second to populate the cross references,

> Docutils is hosted on Sourceforge, and uses a mailing list for all conversations as well as code patches etc. This can make contributing upstream improvements tedious and time-consuming.

Definitely. Hopefully, if enough 'pressure' is applied they would move to GitHub.

**Comment by choldgraf** [comment]
Two quick responses to your points, which I generally agree with:

> LaTeX for example is not always the simplest to use.

I think one of the big challenges in this project will be to choose the right level of power / customizability so that we get *just enough* of the features people want without becoming too complex. If we create something that is just as complicated to configure as Latex (or bookdown?) then we've failed.

> I'd say the Sphinx documentation is pretty decent, if you fully read it

My 2 cents: documentation can be complete without being good. The question isn't "is the information in there somewhere", the question is "how easy is it to find an answer to my question quickly". Most users have extremely short attention spans, and if it requires digging into docs in order to find something they just won't do it.

**Comment by chrisjsewell** [comment]
> I think one of the big challenges in this project will be to choose the right level of power / customizability so that we get just enough of the features people want without becoming too complex.

Absolutely, and as we've recently discussed, for this I think it's important to have some very clear use cases/workflows in my mind.

**Comment by chrisjsewell** [comment]
it great that docutils is so much better now 😒 (sarcastic face)
