### ISSUE TITLE
Build markdown-it-myst into UIs

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#184]
Once [`markdown-it-myst`](https://github.com/executablebooks/markdown-it-myst) is ready for alpha-level using, we could consider wrapping it in a simple extension for VSCode or JupyterLab to get "markdown previews" of MyST markdown in editors.

Perhaps @chrisjsewell knows how to accomplish the former? And we maybe we could get guidance from @agoose77 or @bollwyvl on how to accomplish this with [jupyterlab-markup](https://github.com/agoose77/jupyterlab-markup)?

I also hear that @rowanc1 has a pretty cool myst markdown support that he is working on for Iooxa ;-)

**Comment by chrisjsewell** [comment]
>  a simple extension for VSCode ... Perhaps @chrisjsewell knows how to accomplish the former?

Heya 👋 , well yes we already have that in https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight.
It would just be a matter of adding to and improving this.

**Comment by agoose77** [comment]
So thanks to all the hard work by @bollwyvl, this should now be pretty straightforward. Perhaps if you were to create a `jupyterlab-markup-myst` repository under this organisation, we could create a first-draft extension.

**Comment by chrisjsewell** [comment]
awesome thanks, happy to help

**Comment by rowanc1** [comment]
Awesome. I will focus on creating some dev-docs over the next few days so that this is easier to jump into! I think it is getting pretty close to "alpha-level" :)

**Comment by choldgraf** [comment]
After a recent conversation with @rowanc1 and @damianavila we decided to create a repository to track to-items and discussion points around integrating MyST into Jupyter interfaces. You can find that here:

https://github.com/executablebooks/jupyterlab-myst

There's no specific implementation or anything yet, but we can use that repository to track the conversation and converge on some more specific ideas.

**Comment by choldgraf** [comment]
Nice @chrisjsewell - the aiida dashboard looks pretty kick-ass
