### ISSUE TITLE
Finding some $$ to fund OS markdown editor work from Iooxa

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#192]
Hey all - @rowanc1 and I had a meeting yesterday to discuss ways that we can get Iooxa some funding to do open source work that benefits the executablebooks project (and ideally Iooxa as well 😅). He came up with the idea of working on a markdown editing interface that is inspired by some of the work he's done at Iooxa, and that could align semantically with MyST markdown.

We are thinking about working on a proposal that could fund some of this work, since I believe it is outside the scope of the original EBP grant from Sloan (at least, I think it would be a significant addition beyond the kinds of things we promised in this grant).

I invite any feedback or comments that folks might have towards this. Would it be useful? Are there any major opportunities for improving the authoring experience we could consider as well? And if anybody knows funders that are interested in putting $$ towards this kind of work please do chime in :-)

@rowanc1 - any chance you have a gif or demo or something to give a better idea what I mean by "markdown editing interface"?

**Comment by rowanc1** [comment]
Put together a little video here:

[![image](https://user-images.githubusercontent.com/913249/101268397-88965700-371f-11eb-844a-960c1f4cb0b8.png)](https://www.loom.com/share/19d7bae166d845f783b370c9db02abb1)


Let me know what you think!!

**Comment by choldgraf** [comment]
This looks really cool - I like the simultaneous MyST Markdown mirroring that's shown below.

How do you imagine the relationship between the explorable interactivity on the JS side vs. the variables that people create in their kernels? Do you see people essentially having two different kernels - one for the Jupyter side and one for the JS side (e.g., instead of using Jupyter widgets)? Or do you imagine two different _kinds_ of pages - one for computational notebooks, and another for interactive JS within text?

**Comment by rowanc1** [comment]
Following up on this, all now open source - building on `markdown-it-myst`:
https://github.com/curvenote/editor

**Comment by choldgraf** [comment]
I am gonna close this one, as I don't think there's a next action to take, but we should open a new issue if there are more funding opportunities. In the meantime we are setting up a contract on the Sloan grant to collaborate around this.
