### ISSUE TITLE
Evaluate the full build process to find steps that can use modular tools

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#21]
A few times we've spoken about how we'd like a modular collection of tools that can work together alone or with more lightweight coordinating functions (like a CLI etc).

This is an issue to discuss where are the major components of that process, and where we'd like to make immediate progress:

https://docs.google.com/presentation/d/1uooAicF2MPl32p2z-_z-behfXHi77tbhvgfKafJiKlY/edit#slide=id.p

That's just a starting point for conversation, happy to iterate there or here!

**Comment by akhmerov** [comment]
Is the notebook format sufficiently flexible to allow inclusion of code within other directives?

Imagine something like

```rst
.. danger::

  Division by zero will always result in a huge explosion.

  .. code-block::

    1/0
```

**Comment by mmcky** [comment]
thanks @choldgraf nice flow diagram. I think we would want to support the concept of nested directives and the example by @akhmerov is a great example. 

The representation of that is something we have worked through in `sphinxcontrib-jupyter` and decided to display the `warning`/`danger` element in a markdown cell above an added `code-block` cell. This works in the sense of displaying content but the code-block isn't really nested. One possibility if we wanted to display nestedness we could add nested level metadata to the block for `html` and `pdf` outputs.

**Comment by mmcky** [comment]
One question re: `future roadmap`. Do you imagine a case where the collection of `ipynb` notebooks could be used alongside a `javascript` or `react` application to render them on the fly for the browser (i.e. a website site built using `ipynb`)? 

In any event the `html` writer would be a static site generator and highly useful.

**Comment by choldgraf** [comment]
re: nested directives, I'd think it should be fine to support them. You'd just need something like:

    ```::directive1
    Some stuff
    ```::directive2
    Some other stuff
    ```
    ```

right? You could suggest some kind of indentation scheme to avoid it being super confusing...

**Comment by akhmerov** [comment]
Sorry, I should have been more specific with the question: if the inner directive maps on a code cell of a notebook, then the two surrounding text cells don't have parseable syntax.

This, IMHO, reduces the usefulness of a notebook format.

**Comment by choldgraf** [comment]
@akhmerov to focus in on that particular topic, I opened up https://github.com/ExecutableBookProject/meta/issues/23 which I think has our latest thinking in it. I'd love to hear your thoughts over there

**Comment by akhmerov** [comment]
Sorry, I started writing there, but my question is more about "what" and not about "how". Specifically: what is your current vision for how the notebook format is going to be used? Is it meant to be edited/acted upon by the user? The Jupyterlab sync in the workflow seems to suggest a positive answer. But in that case: should the user also be editing the non-executable input in the notebook? 

For that an ability to preview would be helpful, but the individual cells in the notebook could likely be impossible to parse.

**Comment by akhmerov** [comment]
Interesting ideas in v2/v2.1!

I have some remarks:

- A question about the `nbrunner` in v2.0: how does the multi-notebook aspect enter the play beyond the obvious `async for notebook in notebooks`?
- A general remark: `imd` is written to map on a sphinx AST. Therefore an `imd/ipynb` sphinx writer would be another component to consider.
- A risk of v2.1 is a possible limitation of the sphinx build pipeline wrt its assumptions of what resources are available at what stage.

**Comment by choldgraf** [comment]
Hey all - we just had another conversation about this and I wanted to report back our current thinking.

I've updated the google slides w/ a diagram of the latest proposed build structure here:

https://docs.google.com/presentation/d/1uooAicF2MPl32p2z-_z-behfXHi77tbhvgfKafJiKlY/edit#slide=id.p

Here is a description of the build process:

* Users write content in either `ipynb` or `markdown` files
* That content is converted to a **cacheing** layer.
  * The layer is basically a little database that keeps track of the contents of the input files, their outputs, and information that is meant to be shared across notebooks (e.g. the value of a variable etc)
  * This cache is then passed to an execution process, that checks the code inside the database and decides whether it needs to re-run a notebook or not. It populates the database with outputs from running the code.
* At this point, we have two things: the original content files + a database containing the outputs from running each content file.
* Sphinx then parses the original content files into the AST. It does not yet have any outputs inside but there is a container for each cell with an identifier that maps onto a cell inside the cacheing database
* A Sphinx transform then traverses the AST, and for each cell, finds the outputs in the cache and inserts them into the AST.
* Now Sphinx has an AST with all of the content + the populated outputs. These outputs are probably mime bundles and the builders will decide what to do with them.
* Finally, the builder gets each mime bundle and then does whatever it wants with it.

The two biggest changes:

* The cacheing layer is no longer a collection of `ipynb` files on disk, but is instead a little database to keep track of the notebook content, outputs, and metadata across notebooks. It would probably be accomplished by writing a "JupyterDB" class that is meant to be an abstract object-oriented representation of notebook components that could read/write to many backend storage options.
* The Sphinx parses the content files directly, and after the content is in the AST, Sphinx then inserts the outputs by pulling them from the cache (probably as a Sphinx transform step).

Would love to know what folks think, particularly @mmcky and @AakashGfude...we can discuss this again as a group tomorrow.

**Comment by akhmerov** [comment]
Thanks for the update. I've couple of follow-up questions:

- Can you provide some motivation for the caching layer design? Why is information meant to be shared across notebooks?
- Which component is responsible for generating the ipynb files to serve to the users for downloading or running on binder?

**Comment by jstac** [comment]
Thanks for putting this together @choldgraf.  It's really useful.

Regarding the diagram, version 3,

* It's not clear how the execution process works for those who are authoring in ipynb.  According to the flow diagram, outputs are inserted without sending them down to the cacheing / execution layer.  But where are they generated, in that case?  Directly by the user?
* I like `imd` as the extension but `myst` would be clearer.

Like @akhmerov, I'm wondering why we need to share the value of variables across notebooks.  I can see that we might want to have supporting notebooks that produce outputs destined for publishing, even though the notebooks themselves are not.  But if that's the use case, then don't we just want access to the output of notebook X from notebook Y?

**Comment by akhmerov** [comment]
> But if that's the use case, then don't we just want access to the output of notebook X from notebook Y?

I would even consider accessing outputs across notebook a hard problem in interface and library engineering. It breaks the core abstraction of the notebook: what you output, you never get back.

**Comment by mmcky** [comment]
Thanks @choldgraf. I think this is evolving in the right direction. I have a few comments and questions below. 

1. For the `JupyterDB` I am assuming we will use the parser to extract the code-blocks from either the `myst` or `ipynb` file. So just to clarify the architecture -- will it work more like (see below). [Please delete the image so as not to confuse this thread if that is not correct]
![image](https://user-images.githubusercontent.com/8263752/74692713-8d475880-523c-11ea-8ed1-ec0d851af8a3.png)

1. one concern with using the database approach is how we might be able to connect users with the error information. Divorcing the execution from jupyter notebooks removes the potential opportunity to dump a user in a running notebook (to diagnose errors) -- similar to `pdb`. I guess the initial approach will be report based -- we can build reports and assemble notebooks with `Traceback` information and one option would be to assemble a notebook and attach to the running kernel used to execute the code blocks.

**Comment by chrisjsewell** [comment]
> To just to clarify the architecture -- will it work more like

No. That's one of the main points; the execution is done outside of sphinx, then sphinx uses both the original source files (to parse syntax) and the `JupyterCache` to query e.g. for outputs it needs to render. 

The point of `JupterCache` is that it is a consistent interface to manage, at a simplistic level, adding and retrieving notebooks from the cache, but also retrieving specific code cell outputs (required by sphinx), and dealing with how you work out if the kernel/code has changed since the last execution (required by the 'executor'), etc.

In https://github.com/ExecutableBookProject/sandbox I've added an initial `jupyter_cache` package (formerly `jupyter_db` and partly copied from https://github.com/ExecutableBookProject/myst_parser/tree/jupyter/jupyter_db) to begin to explain and prototype.

There is an abstract base class in: https://github.com/ExecutableBookProject/sandbox/blob/master/jupyter_cache/base.py. This just defines this 'consistent' interface. Then I've created two 'implementations' of this interface:

- https://github.com/ExecutableBookProject/sandbox/blob/master/jupyter_cache/json/main.py: this stores directly the notebooks to a folder, but also has a central JSON file; to for example provide a mapping of these notebooks back to URIs of the original files.
- https://github.com/ExecutableBookProject/sandbox/blob/master/jupyter_cache/sql/main.py; which has the SQL backend I have already talked about.

Note with both backends; they can return requested notebooks (as `nbformat.NotebookNode`), that the executor can use and potentially do this `pdb` type error feedback.

We can discuss this in the office shortly 😄

**Comment by mmcky** [comment]
OK thanks @chrisjsewell. I guess I didn't understand how the `myst`/`imd` file gets parsed for extraction of the code related blocks for the `jupytercache` engine.

**Comment by chrisjsewell** [comment]
Yeh I certainly wouldn't say there is a complete solution to this yet. But the working idea is that:

- `jupytext` would be responsible for the two-way mapping; it would be 'better' to use `myst_parser`, but then you lose the consistent approach to two-mapping for multiple fie types.
- You pass in source notebooks and/or `myst` documents into the `JupyterCache`; if `myst` document, then it is first converted to a notebook by `jupytext`.
- The 'executor' is parsed the `JupyterCache`, which it can use to query for notebooks with missing or 'outdated' outputs. It then executes these as it sees fit, and parses back the executed notebooks to the cache.
- Sphinx parses the source notebooks and/or `myst` documents (parsing the source documents rather than cached ones makes it easy to report errors, e.g. by line number, and use its standard machinery for working out which files have changed, using file mtime).
- Sphinx is also 'supplied' with the cache. Then during whatever step of the sphinx process when it requires a code cell output, it queries the cache for it (e.g. by docname and code cell index).

**Comment by chrisjsewell** [comment]
> why we need to share the value of variables across notebooks.

I would get hung up on this, it’s not the main goal of the cache. But it would be made possible by the cache, and is used for example in the nteract/scrapbook project. 

> Which component is responsible for generating the ipynb files to serve to the users for downloading or running on binder?

Probably the cache. 

> Would the lifecycle of the JupyterDB be managed by sphinx or something else?
 
The cache is persistent, when you initialise the `JupyterCache` (with a path to the persistent files) it either uses those or creates new files.

**Comment by chrisjsewell** [comment]
@mmcky and @AakashGfude can you point me towards the current code you've written for cacheing (where you were using hashes of code cells)

**Comment by AakashGfude** [comment]
@chrisjsewell , it is in [this](https://github.com/QuantEcon/sphinxcontrib-jupyter/tree/redesign) branch of `sphinxcontrib-jupyter` . The builder `sphinxcontrib/jupyter/builders/jupyter_code.py` handles caching at present. The file cached are `.codetree` files in JSON format, where hashes of input code cells, are used as keys.

**Comment by akhmerov** [comment]
@AakashGfude how does that cache invalidate the outputs cells that come after the modified cell? I thought that usually when every single cell is updated in a notebook, the whole notebook must be rerun.

**Comment by akhmerov** [comment]
> The cache is persistent, when you initialise the JupyterCache (with a path to the persistent files) it either uses those or creates new files. So technically you shouldn’t need to manage it’s lifecycle as you just pick it up or let it go whenever you need.

I think the users will most definitely need to invalidate the cache due to something outside of its control changing, be it other scripts within the repository that the notebooks import, dependency version, or even external dataset that the notebooks download.

So deletion from the cache must be an option, do you agree? If yes: would the users be able to only nuke the complete cache, or would the cache allow a more fine-grained control over its state?

**Comment by chrisjsewell** [comment]
> I think the users will most definitely need to invalidate the cache... So deletion from the cache must be an option, do you agree? If yes: would the users be able to only nuke the complete cache, or would the cache allow a more fine-grained control over its state?

Yep agreed. There is already a `remove_notebook` method on the interface, but yes I would envisage `invalidate_cache()` and `invalidate_notebook()` methods.

**Comment by AakashGfude** [comment]
> @AakashGfude how does that cache invalidate the outputs cells that come after the modified cell? I thought that usually when every single cell is updated in a notebook, the whole notebook must be rerun.

@akhmerov you are right. The whole notebook is rerun when there is a change of code in any cell of that notebook. 
The change of code is usually detected by normalizing the input code cell, and generating the hash code, and then comparing the hash code with the cached version of that input cell. If the hash codes do not match, the whole notebooks' code cells are rerun, including the ones before that cell.

**Comment by akhmerov** [comment]
> No. That's one of the main points; the execution is done outside of sphinx, then sphinx uses both the original source files (to parse syntax) and the JupyterCache to query e.g. for outputs it needs to render.

Do I understand correctly, that there will also be an overarching library that manages the whole build process, of invoking first the `jupytext`, then the notebook execution, and finally `sphinx-build`? This seems to follow from the description, but isn't clear to me from the pipeline schematics.

> Yep agreed. There is already a `remove_notebook(uri)` method on the interface, but yes I would envisage `invalidate_cache()` and `invalidate_notebook(uri)` methods.

Implementing UI for such granular control seems labor-intense and also increases the tool complexity. Do you think the benefits are justified, compared to the "nuke all" option?

Also if the execution is not under control of sphinx, then how does one guarantee that the outputs are up to date when the sphinx-build is invoked? By only calling it via the external tool?

I also mentioned the question elsewhere: but do you consider serving files that are not jupyter outputs?

**Comment by choldgraf** [comment]
Now that we have a prototype for the cache working, perhaps we could move conversations that are specific to "execution and cacheing" over to there?

https://github.com/executablebookproject/jupyter-cache

I think it'll make it easier to keep track of these conversations and brainstorm ideas, as opposed to having them embedded as a part of a thread on the full build system.

**Comment by choldgraf** [comment]
Hey all - I updated the latest build pipeline to make some things clearer, just FYI

https://docs.google.com/presentation/d/1uooAicF2MPl32p2z-_z-behfXHi77tbhvgfKafJiKlY/edit#slide=id.p

**Comment by akhmerov** [comment]
Thanks! Can you comment on the current vision wrt the bidirectional mapping? It's gone from the pipeline.

As far as the current scheme goes, my only concern is that it may be too hard to make the cache work well, but judging by the pipeline, it also seems to be easy to swap out entirely.

Also a small detail: perhaps include the steps for building notebooks in step 4?

**Comment by akhmerov** [comment]
I also found it instructive to compare the V3 pipeline with the current state of jupyter-sphinx. Here's what it does.

1. It reads in rst, no overlap there.
2. It generates a *somewhat different* partial sphinx AST
3. Executes the code (at an incorrect place, as pointed out by @chrisjsewell)
4. Generates the full sphinx AST
5. Writes HTML and PDF

Therefore if it makes step 3 an entrypoint that allows to replace execution with cache lookup and harmonizes the format of the partial sphinx AST, it would be compatible with the planned pipeline.

**Comment by choldgraf** [comment]
nice - makes sense to me. I think for 3, the main thing I'd like is containers around the cell, cell inputs, and cell outputs. I've found that being able to select any of these 3 things helps with designing cleaner CSS and JS rules for HTML sites.

What are the major ways that the two projects diverge on this point? Anything deal-breaking?

**Comment by akhmerov** [comment]
> What are the major ways that the two projects diverge on this point? Anything deal-breaking?

Nothing comes to mind. The main restriction of jupyter-sphinx at the moment is the rst markup, and the feature set that it enables. I wouldn't like to break compatibility without a good reason, but even then the project isn't at a stable release point, so if there is a good reason, all bets are off.
