### ISSUE TITLE
Broken link on https://executablebooks.org

### ISSUE THREAD

**Issue by lexnederbragt** [executablebooks/meta#227]
**Describe the bug**

On https://executablebooks.org/en/latest/, the link to `our latest updates`, which is https://executablebooks.org/en/latest/updates/index.html, is broken.

**To Reproduce**

1. Go to https://executablebooks.org
2. Click on `our latest updates`.
3. See error

**Expected behavior**

A webpage with the latest updates.

**Environment**

Safari 14.0.2, Mac OS 10.14.6 (but likely the same ing other browsers)

**Comment by choldgraf** [comment]
Thanks for catching this 👍
