### ISSUE TITLE
Numbering figures and equations by chapter

### ISSUE THREAD

**Issue by mikheyev** [executablebooks/meta#251]
Currently, figures and equations are numbered continuously. However, in long books it may help to have chapter-specific numbering. E.g., Chapter 1 would have equations prefixed with "1", e.g., "1.1", "1.2". This helps orient within the document, making links outside the current material more explicit.

**Comment by mmcky** [comment]
thanks @mikheyev -- are you using [sphinx_multitoc_numbering](https://github.com/executablebooks/sphinx-multitoc-numbering) on your project?

It has helped us get `equations` numbered with a chapter prefix such as `12.1`. I will have to put a minimal example together to check figure numbering (as we don't have any captioned figures).

**Comment by mikheyev** [comment]
It works! Thank you so much. I installed it and added the extension to the `_config.yml`

```
sphinx:
  extra_extensions:
  - sphinx_multitoc_numbering
```

**Comment by mmcky** [comment]
great news -- thanks @mikheyev
