### ISSUE TITLE
Create a Sphinx extension for a single ToC file

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#292]
In #285 we discussed that one way Jupyter Book deviates from Sphinx is in using a single Table of Contents file for the whole book, rather than embedding `{toctree}` in each page w/ subsections.

This is an issue to discuss whether we should make this a standalone Sphinx extension rather than a Jupyter Book feature.

Technically speaking, I don't think that this would be too hard. We currently use this function to inject `toctree`s in pages:

https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/toc.py#L41

and then call this on the `source-read` step:

https://github.com/executablebooks/jupyter-book/blob/a3065b134c6f6b1b6b467ca0652778709d156c7f/jupyter_book/__init__.py#L32

In addition, @AakashGfude wrote a `TableOfContents` node that will let users display the table of contents in the final page:

https://github.com/executablebooks/jupyter-book/blob/a3065b134c6f6b1b6b467ca0652778709d156c7f/jupyter_book/directive/toc.py#L19

I believe that this could *all* be encapsulated in a single Sphinx extension in a fairly straightforward manner. Would others find this useful? @ericholscher @pradyunsg any thoughts?

**Comment by chrisjsewell** [comment]
yeh I'll do this

**Comment by choldgraf** [comment]
I think that if we separate it out into another extension, it might also be an opportunity to reduce some technical complexity a bit. I still suspect there is a more elegant pattern to follow here than to create a *new* table of contents directive that only displays, but does not define, the table of contents...

**Comment by AakashGfude** [comment]
@choldgraf should I move the handling of `tableofcontents` directive in the case of latex to https://github.com/executablebooks/jupyterbook-latex then. Might as well make that repo encompass as many latex features as we can.

>  I still suspect there is a more elegant pattern to follow here than to create a _new_ table of contents directive that only displays, but does not define, the table of contents. 

Sorry, did not get this point clearly.

**Comment by choldgraf** [comment]
let's see how the implementations for a sphinx extension looks like first and then we can see if / how we'd need to change Jupyter Book to accommodate it?

> Sorry, did not get this point clearly.

I'm saying that it feels a bit clunky for us to basically be creating doctree structures that look something like this:

```
<title>
<body>
<tableofcontents that was created from a tableofcontents directive>
<body>
<toctree we inserted manually, but that is hidden>
```

I feel like we _should_ be able to just make the `toctree` itself go to a different place rather than requiring a new kind of docutils node...just not sure exactly how. Does that make sense?

**Comment by AakashGfude** [comment]
Thanks for the clarification @choldgraf . Though at present, we are in fact using the `<toctree we inserted manually, but that is hidden>` to create `tableofcontents` directive, by cutting it and pasting it there. The directive name is just an embellishment for displaying the toctree we have manually inserted. https://github.com/executablebooks/jupyter-book/blob/master/jupyter_book/directive/toc.py#L176

**Comment by choldgraf** [comment]
amazing! in that case I think you found a good solution that I was just misunderstanding :-)

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/sphinx-external-toc/issues/1

**Comment by chrisjsewell** [comment]
done
