### ISSUE TITLE
Review/document existing online texts that we find attractive or interesting

### ISSUE THREAD

**Issue by jstac** [executablebooks/meta#3]
*  https://quantum.country/qcvc

**Comment by choldgraf** [comment]
Shall we keep this issue as a "todo" item, and populate a new "wiki" page with the items we think up?

**Comment by choldgraf** [comment]
here are a few other things I've noticed over time:

* https://components.ink/ and https://row1.ca/explorables
* http://blog.juliusschulz.de/blog/ultimate-ipython-notebook
* https://edwardtufte.github.io/tufte-css/
* http://worrydream.com/ClimateChange/
