### ISSUE TITLE
Utilize the tufte style for latex as well? 

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#30]
I noticed that there is also a tufte latex package. The tufte style is a heavy influence for the layout of jupyter book. I wonder if we could utilize this package (maybe optionally) for some consistency in the outout look and feel https://github.com/Tufte-LaTeX/Tufte-LaTeX

 ping @mmcky and @rossbar who are both interested in PDF output

**Comment by jstac** [comment]
Nice, although personally I prefer justified text (paragraphs aligned at both left and right margins) in my PDF documents.  It's more standard for articles and published books.

**Comment by choldgraf** [comment]
for sure - I think it's something that could be configurable if we wish

**Comment by rossbar** [comment]
Nice find! I haven't thought too deeply about specific layouts/formats that would be best suitable for technical textbooks, but I gave it a quick glance and do like the general aesthetic. At a higher level - I do like the idea of try to make the theme of generated pdf and website "feel consistent". Having high-quality outputs with a consistent look/feel would (in my opinion) be a strong point of appeal to a wider range of potential authors.

**Comment by mmcky** [comment]
Thanks @choldgraf -- the tufte styles look nice. My thinking is to include these as `styles` or `themes` -- and possibly have a few options available -- but this may well be a nice default. Particularly if it shares some harmony with `HTML` tufte layouts. 

Once we get a prototype translator working -- it will be important to see how we can improve ways of passing settings and configuration to `Latex` and `HTML` builders.
