### ISSUE TITLE
exception: No module named 'sphinx_copybutton'

### ISSUE THREAD

**Issue by fmrtl73** [executablebooks/meta#310]
**Describe the bug**

Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')

**To Reproduce**
I followed the simple instructions to  `pip install sphinx-copybutton` and added the 'sphinx_copybutton' to my extensions: 
```
extensions = [
#    'sphinxmark',
    'sphinxcontrib.spelling',
    'sphinx_rtd_theme',
    'sphinx_copybutton',
]

When I run `tox -e docs` I get the following error:
```

Extension error:
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')
```
I also tried adding `sphinx_copybutton` to my requirements.txt but that did not help.

**Expected behavior**
It should just work as described in the docs.

**Environment**

- Python Version [e.g. 3.7.1]: 3.9
- Operating System: mac osx 10.15.7

**Comment by chrisjsewell** [comment]
Heya, what's in your tox.ini? This creates a separate virtual environment, and so if you haven't specified to install it in there, then it won't find it.
