### ISSUE TITLE
Use Datatables instead of Tabulator for our feature voting board

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#322]
# Background

Our feature voting board is (IMO) super useful, but also quite brittle. It seems to be broken often. It's also a bit complex to understand as [we hand-create the table in javascript](https://github.com/executablebooks/meta/blob/master/docs/_templates/layout.html#L17).

# Proposal

I think a simpler approach would be to instead use the following workflow:

1. Write a Python script that uses `ghapi` to pull the list of issues, sorted by 👍 , across repositories, and writes this to a CSV file
2. Call this script as a part of our docs build so the list is updated each time we build the docs.
3. Use a [`csv-table` directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#id4) to load that file as a table in the [features voting page](https://executablebooks.org/en/latest/feature-vote.html)
4. Load and use [datatables](https://www.datatables.net/) on that page, and point it to the table, to make it sortable.
5. Automate the documentation build so that the table is (at least daily) up to date

**Comment by chrisjsewell** [comment]
If you can improve it then great, but one thing to note: where are you store and access the Github API key from, which is currently in Github secret: https://github.com/executablebooks/meta/settings/secrets/actions? and if you call it for every build (including PR commits) you run the risk of running out of "access credit"
