### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#33]
We've discussed having a website as a "meta" documentation for the project, so it seemed like the "meta" repository might be a good place for it :-)

I just added a barebones documentation site to this repository, it's hosted here:

https://executablebookproject.readthedocs.io/en/latest/

A few questions:

* +1 to hosting it in this repo?
* Any structural changes we should make to the site in general?
* When content is fleshed out, how about pointing this to `ebp.jupyterbook.org`?

**Comment by jstac** [comment]
Thanks @choldgraf for putting this together.

So, I'm trying to work out how all the parts fit together and I wanted to clarify a few things.  (Perhaps this isn't the best place for this discussion so feel free to shift it elsewhere.)

In my mind, ExecutableBookProject is an organization that helps us manage all aspects of the project we took on in our grant proposal, including 

* managing grants
* hosting and developing some software components
* gathering related blog posts and discussion, etc.

It's of interest to some developers, including us.

But what does the *user* think of when they invoke the controller in [this system](https://docs.google.com/presentation/d/1uooAicF2MPl32p2z-_z-behfXHi77tbhvgfKafJiKlY/edit#slide=id.p)?  What do they tell their friends they used when someone asks how they made their shiny new book?

From previous discussions, I had the impression that you would be willing to have the name "Jupyter Book" play this role, @choldgraf.  Is that right?  So the CLI would be invoked as `jupyter-book my_textbook` or similar?  

In this case, 99% of our users will know nothing about ExecutableBookProject.  Nor will they need to concern themselves with it in any way.  Correct?

If that's true, perhaps it should be hidden from them, so they don't get confused.  Users are easily confused (speaking from personal experience).

So, if this is user-facing documentation on how to build a book from source, perhaps it should be hosted at `docs.jupyterbook.org` and the title should be "Jupyter Book"?

(Or, option 2, ExecutableBookProject becomes the name that users associate with the tool set and we call the controller process ``ebp``.  That's OK with me too.  I just want to clarify these issues.)

**Comment by choldgraf** [comment]
@jstac in my mind, this documentation is purely project-focused. It is about the people, and the goal, and the the deliverables of the EBP. It's not about any one specific tool, but a place to keep meta information about the team/process that created those tools. E.g., it's a place where we might post updates and things like this.

I *also* imagine a different documentation sight that is specifically for the "controller" process, and yep I am +1 on this being called "Jupyter Book". I agree that users of the tool don't need to know anything about EBP, which I didn't want to host this repo's documentation at `docs.jupyterbook.org` but instead chose a URL that would be specific to the EBP. 

Put another way, I imagine that the EBP documentation is specific to this grant, and will likely be sunsetted in some fashion once the grant is over. It's something we could point to as a summary of what we did during the grant. However, the constellation of tools around it will continue to grow and update and that's what should be the user-facing documentation.

Does that make sense? Perhaps this is overkill?

**Comment by jstac** [comment]
Thanks @choldgraf , this is exactly the clarification I was after.  All makes sense to me and I agree we should proceed as you suggest.

**Comment by choldgraf** [comment]
OK cool - I just made the site live at https://ebp.jupyterbook.org/en/latest/

Will work on the content etc in the coming days, PRs definitely welcome!

**Comment by chrisjsewell** [comment]
this is up and running
