### ISSUE TITLE
Give Sloan Foundation some more love

### ISSUE THREAD

**Issue by jstac** [executablebooks/meta#397]
**Is your feature request related to a problem? Please describe.**

Their support for the project is not very visible  on the EBP or JB sites.  At the same time, it was crucial in getting things off the ground.

**Describe the solution you'd like**

Their logo and/or a thanks on a prominent public facing page.

**Comment by choldgraf** [comment]
100% this is super important

**Comment by choldgraf** [comment]
I took one stab at this by adding the Sloan logo in https://github.com/executablebooks/jupyter-book/pull/1377 - if that's a good pattern we can add it to the EBP website too.
