### ISSUE TITLE
Investigate ipypublish

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#4]
@jstac recently mentioned that there's another tool out there in the Jupyter / Python ecosystem that's quite relevant. It's called [ipypublish](https://ipypublish.readthedocs.io/en/develop/) and seems like it might be useful as a part of the book publishing process. This is an issue to investigate it and discuss our takeaways.

It seems like ipypublish has a bunch of different build systems depending on the outputs that's requested. It uses Jupyter Notebooks as an input, and [converts them to outputs](https://ipypublish.readthedocs.io/en/develop/nb_conversion.html) using some combination of **nbconvert**, **pandoc**, and **sphinx**. They've also written a number of Pandoc filters that [parse markdown content](https://ipypublish.readthedocs.io/en/develop/markdown_cells.html#writing-markdown) and that could be used independently of the ipypublish build process.

I'll try installing and running a few outputs etc on my machine - would love to hear thoughts from anybody else who's used it or looked through it as well.

**Comment by choldgraf** [comment]
I found this diagram to be useful in wrapping my head around the ipypublish build process:

https://ipypublish.readthedocs.io/en/develop/custom_export_config.html#outline-of-the-process

It looks like a lot of the heavy lifting is done with a combination of:

* [nbconvert preprocessors](https://ipypublish.readthedocs.io/en/develop/api/ipypublish.preprocessors.html) (e.g., here's [one that seems to resolve Latex-style references](https://github.com/chrisjsewell/ipypublish/blob/develop/ipypublish/preprocessors/latextags_to_html.py))
* [pandoc filters](https://ipypublish.readthedocs.io/en/develop/api/ipypublish.filters_pandoc.html#submodules).

I'm not sure exactly when Pandoc vs. nbconvert is used however. I'd love to be able to pick out bits and pieces of this for Jupyter Book - thus far I've tried to avoid depending on Pandoc to reduce the amount of overhead involved with generating outputs, but these filters are compelling...

**Comment by choldgraf** [comment]
I also opened up [this issue in ipypublish](https://github.com/chrisjsewell/ipypublish/issues/111) asking a bit about the HTML generation steps. Will let you know if I hear anything from this (and please do chime in there if you have ideas as well)

**Comment by chrisjsewell** [comment]
and you never did hear from them

**Comment by choldgraf** [comment]
:-)
