### ISSUE TITLE
plans to add css for @media print?

### ISSUE THREAD

**Issue by phaustin** [executablebooks/meta#41]
We're using some simple templates with nbconvert 6 to add page breaks and page counters that work with headless chrome, and would like to make it as easy as possible to move these over to ebp.  Are there plans for css3 @page styling?   For example here's something that [works with counters and page breaks](https://github.com/eoas-ubc/paged_trio/blob/121c667515881e0ac2c99e18faae4f476389b464/pagelib/project_templates/nbconvert/templates/printit/index.html.j2#L61-L114).    We also needed to borrow this [mathjax2 config](https://github.com/eoas-ubc/paged_trio/blob/121c667515881e0ac2c99e18faae4f476389b464/pagelib/project_templates/nbconvert/templates/printit/index.html.j2#L16-L51) from R pagedown to get headless chrome to render correctly on multiple pages.

**Comment by choldgraf** [comment]
Hey - thanks for reaching out! We have abstract but not concrete plans 😊 we definitely do want to support headless printing (and printing the html directly from the page). Jupyter book has features like this too so we can probably reuse that js/css as well as yours

**Comment by choldgraf** [comment]
I think that the place where this CSS would be added is somewhere here:

https://github.com/ExecutableBookProject/cli/tree/master/jupyter_book/theme

That repo is the command-line interface that people will use, and the most "user-facing" piece of the puzzle. My hope is that we can use a slightly modified version of the [pydata sphinx theme](https://pandas-sphinx-theme.readthedocs.io/), so we could either add our own CSS via the CLI repo, or upstream an improvement to that theme.

**Comment by phaustin** [comment]
thanks for that -- we'll try those with nbconvert and trio_cdp and let you know if we hit any issues.

**Comment by choldgraf** [comment]
another note: looks like we could link a CSS file explicitly for "print" in Sphinx: https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-application-sphinx-add-css-file
