### ISSUE TITLE
Submit at PyData Global abstract

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#444]
The [PyData Global Conference](https://pydata.org/global2021/) is at the end of October this year. This could be a good opportunity to give a talk about recent updates in the Executable Books ecosystem, and boost its presence in the Python community.

The deadline for proposals is **Sunday, August 15th**

# Instructions for giving talks

_From their website_

Talks are 30-minute sessions including time for Q&A. A talk proposal is a short description of a talk that is aiming to convince someone to part with 30 minutes of their time, in order to learn about something. A good proposal should disclose:

- The topic (the WHAT) and WHY it is interesting
- The audience to WHOM the talk is addressed
- The TYPE of talk (lots of maths, hands-on, etc) and possibly the tone (light-hearted, informative etc)
- The TAKEAWAY, a.k.a. what will I learn

There are two parts to a proposal:

- Brief Summary – This informs attendees what the talk is about. Discloses the topic, domain and overall purpose. This is at most a few lines long, and will be printed in the conference programme.
- Description – This is a self-contained statement that summarises the aspects of the talk. It should be structured and present the objective of the talk, its outline, central thesis and key takeaways. After reading the description, the audience should have an idea of the overall presentation and know what to expect. The description should also make clear what background knowledge is expected from the attendees. Both this and the summary will be included in the talk details online.

# Actions

- [ ] Do we think this is a good opportunity to showcase updates in the Executable Books world?
- [ ] Is anybody else interested in giving this talk?
- [ ] ...fill in if we decide we want to give the talk.

**Comment by chrisjsewell** [comment]
yep sounds good to me 👍

**Comment by jstac** [comment]
:+1: @choldgraf , I reckon you are the right man for the job.

**Comment by choldgraf** [comment]
hey all - unfortunately the deadline has passed and I didn't have the bandwidth to put together an abstract. I am very short on EBP time right now. We should find another conference to submit to in the future to highlight the latest changes. Maybe SciPy 2022 or something? Gonna close this issue
