### ISSUE TITLE
Team Meeting - September

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#465]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: 2021-09-02 at 7AM Sydney Time (or [your timezone](https://arewemeetingyet.com/Sydney/2021-09-02/07:00/EBP-Team-Meeting)).
- **Google Calendar link**: https://calendar.google.com/event?action=TEMPLATE&tmeid=NWtrMmhibXB2MnYxZDcxNDN2bGI1bjkxdHZfMjAyMTA5MDFUMjEwMDAwWiAybmJoMDBoaDkwMjB1NjIybnQwcDVxaGJla0Bn&tmsrc=2nbh00hh9020u622nt0p5qhbek%40group.calendar.google.com
- **Agenda+Video links**: [HackMD](https://hackmd.io/THymMOAmSICp8rJdB6_Z1w?edit)

If you'd like to discuss something at the meeting, please add an item to the agenda!

# Before the meeting

- [ ] Update dates and make sure HackMD information is correct
- [ ] Create an event link from Google Calendar and paste above.
- [ ] Add discussion items
  
 # After the meeting

- [ ] Turn any follow-ups into issues/comments/etc
- [ ] Copy the meeting notes to the docs
- [ ] Remove notes from HackMD to prep for next meeting
- [ ] Create issue for the next team meeting and pin it
- [ ] Done 🎉

**Comment by chrisjsewell** [comment]
next meeting datetime?

**Comment by choldgraf** [comment]
Oops - just opened an issue about it. It's on Wednesday: https://github.com/executablebooks/meta/issues/507
