### ISSUE TITLE
Make some pre-releases?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#47]
In our last meeting, @jstac suggested that we could release the myst-parser and myst-nb projects in a "public beta" fashion, relatively soon. I think it could be a good idea to get some of these tools out there sooner than later. What do people think about:

* In the next few days, start telling twitter, open-source colleagues, etc about the MyST-parser for Sphinx
* After @AakashGfude's PR lands in MyST-NB and we have a week-or-so to test it out, do the same thing for MyST-NB

What do folks think about that?

And on the second point, we should also reach out to the `nbsphinx` project and see if they have any ideas for how we could dovetail our stacks into one another.

The one question I have here, is whether @chrisjsewell thinks that recent conversations about `markdown-it-py` should delay the "announcement" of MyST and the MyST parser. Chris, what do you think?

**Comment by jstac** [comment]
+1 in principle but it depends on @chrisjsewell .  We all know things can happen fast when he gets an idea in his head :bulb:

**Comment by chrisjsewell** [comment]
See  ExecutableBookProject/markdown-it-py 😄 Its largely done (see the README for details) and in `markdown_it/doc_renderer.py` is the initial port of the docutils renderer, which works exactly the same as the mistletoe one, and its now faster than mistletoe.

The main niggling issue is  ExecutableBookProject/markdown-it-py#1.

Its pretty nice that you can configure any aspect of the syntax. I could envisage some of that configurability eventually bubbling up to the CLI.

**Comment by chrisjsewell** [comment]
Note the footnote extension also support the inline feature discussed in https://github.com/ExecutableBookProject/MyST-Parser/issues/98#issuecomment-593584424 (will have to see how this fits in with the docutils renderer)

**Comment by jstac** [comment]
That's awesome, love your work @chrisjsewell !

@najulizu, please not this simplified syntax.  Please add some whitespace between equation and `$$`.

**Comment by choldgraf** [comment]
Ah one other thing - @chrisjsewell mentioned that markdown-it-py is nearly ready to go, but there's still another step of making the myst-parser parse using it, right?

**Comment by jstac** [comment]
Best to leave this until after the first round of blog posts / publicizing?

**Comment by choldgraf** [comment]
That was the question I wanted to ask @chrisjsewell - I guess the question is whether we think that switch will make any kind of differece for myst-parser...I don't *think* so, I think it's a purely-backend thing, but just wanted to make sure

**Comment by chrisjsewell** [comment]
done and dusted
