### ISSUE TITLE
Early adopters / projects to support / target 

### ISSUE THREAD

**Issue by jstac** [executablebooks/meta#49]
It won't be very hard to convert some existing texts built using bookdown over to jupyter-book, after switching their Rmd to MyST.

For example, @najuzilu is currently studying from https://introtcs.org/public/, which is an introductory CS course at Harvard.  I don't think it would be too time consuming to switch it over.  The first obvious benefit for the students would be downloadable jupyter notebooks corresponding to each lecture.

**Comment by choldgraf** [comment]
@fperez had some projects in mind that could be interested as well. Fernando could you post any ideas here?

**Comment by akhmerov** [comment]
I plan to switch https://topocondmat.org and https://solidstate.quantumtinkerer.tudelft.nl/ soon. Just need to finish teaching :)

**Comment by fperez** [comment]
I just pinged Randy via email, but I also presume you're already in touch with Greg Caporaso? His [Introduction to Applied Bioinformatics](http://readiab.org) was another early example of this...

Same with @unpingco, whose signal processing and stats books were, I'm pretty sure, the very earliest ones done with/as Jupyter Notebooks...

Note that the [gallery in the Jupyter wiki](https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks) might also have a few more relevant ones...

**Comment by jstac** [comment]
Those are beautiful books @akhmerov.  I started browsing and got hooked :-)
