### ISSUE TITLE
Team Meeting - October

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#507]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: 2021-10-07 at 7AM Sydney Time (or [your timezone](https://arewemeetingyet.com/Sydney/2021-10-07/07:00/EBP-Team-Meeting)).
- **Agenda+Video links**: [HackMD](https://hackmd.io/THymMOAmSICp8rJdB6_Z1w?edit)
- **Google Calendar link**: [event link](https://calendar.google.com/event?action=TEMPLATE&tmeid=NWtrMmhibXB2MnYxZDcxNDN2bGI1bjkxdHZfMjAyMTEwMDZUMjAwMDAwWiAybmJoMDBoaDkwMjB1NjIybnQwcDVxaGJla0Bn&tmsrc=2nbh00hh9020u622nt0p5qhbek%40group.calendar.google.com), [team calendar link](https://calendar.google.com/calendar/u/0?cid=Mm5iaDAwaGg5MDIwdTYyMm50MHA1cWhiZWtAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

If you'd like to discuss something at the meeting, please add an item to the agenda!

# Before the meeting

- [ ] Update dates and make sure HackMD information is correct
- [ ] Create an event link from Google Calendar and paste above.
- [ ] Add discussion items
  
 # After the meeting

- [ ] Turn any follow-ups into issues/comments/etc
- [ ] Copy the meeting notes to the docs
- [ ] Remove notes from HackMD to prep for next meeting
- [ ] Create issue for the next team meeting and pin it
- [ ] Done 🎉

**Comment by mmcky** [comment]
@choldgraf I think we need to update the HackMD link to be a clean agenda.

**Comment by choldgraf** [comment]
Yep will do it today before the meeting 👍
