### ISSUE TITLE
Practice around supported Python and Sphinx versions

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#513]
### Description

Two of the big dependencies for our stack are Python and Sphinx. We should decide on a policy to follow for "officially" supporting Python and Sphinx versions in our test suites.

#### Python

In https://github.com/executablebooks/meta/issues/306 @chrisjsewell suggested that we use the [Python end-of-life dates](https://devguide.python.org/#status-of-python-branches) to decide which versions of Python to support.

I suggest that we do the following:

- Use the EOL dates to *drop* support for Python versions
- Test against the last 3 minor Python releases (so from today, it'd be 3.10, 3.9, 3.8)
- Document this practice

#### Sphinx

IN https://github.com/executablebooks/meta/issues/306 we had some discussion and this seemed to land on officially supporting the **last 2 major versions of Sphinx**.

### Tasks

- [ ] Any objections / edits to the practice described above?
- [ ] Document this in the contributing guide

**Comment by choldgraf** [comment]
(I also don't feel that strongly that we need to only test 3 python versions, if others don't think it's a big deal)

**Comment by chrisjsewell** [comment]
Another thing I would suggest is that the (documented) aim should be for the the support to come within maybe 6 months of the release of new versions, e.g. as soon as sphinx v4 came out there were people asking for its support, which is understandable, but obviously depending on the number of breaking changes it's unlikely going to be feasible to roll out support for all JB dependencies within days
