### ISSUE TITLE
Sphinx 3 is out

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#53]
Sphinx just released their public 3.0 release:

https://pypi.org/project/Sphinx/3.0.0/

We should make sure that things work with Sphinx 3.0...I think many of the sub-repositories are pinned to sphinx<3.0

**Comment by chrisjsewell** [comment]
Eventually yes but definitely not yet. (a) we need to wait until dependent packages, like shinxcontrib-bibtex, also support it, and (b) best to wait until ~3.1 is released and they fix a number of the new issues I’ve seen crop up like
sphinx-doc/sphinx#7429

**Comment by chrisjsewell** [comment]
Just found out about this deprecation list which should come in handy: https://www.sphinx-doc.org/en/master/extdev/deprecated.html. We'll want to go through all packages with sphinx dependencies and search for these imports etc

**Comment by choldgraf** [comment]
Yeah, and probably best to start lowest in the stack (the parser) and work our way up to the highest (prob jupyter book) over time

**Comment by chrisjsewell** [comment]
Just waiting on https://github.com/executablebooks/MyST-NB/pull/226 then https://github.com/executablebooks/jupyter-book/pull/871
But I think this issue can be closed here
