### ISSUE TITLE
Technical strategy for the final year of the Sloan grant

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#535]
### Description

The Sloan grant that launched this project is going to come to an end in October 2022. While #493 is focused around community strategy and dynamics, we also need to come up with a **technical strategy** for what kinds of development to prioritize in the final year of the grant. This is an issue to gather feedback from folks about where they think we should focus our efforts.

A few things that we should consider:

- For the deliverables in the original grant, we likely do not need to develop significant new features, so we have flexibility on what we work on.
- We should assume that nobody will be paid to work on this project at more than, say, 20% time. We might be able to get funding, but I doubt that this will go towards dedicated FTEs in the way that it has in the past.
- Are there any major technical pushes that we need to make that are particularly well-suited to dedicated development time? What are things that won't happen with volunteer labor, but could happen with dedicated time?
- Are there any major opportunities to improve the maintainability of the stack, and the likelihood that other contributors can join the community as developers?

**Comment by mmcky** [comment]
**`MyST` specification**

1. (most important) base `MyST` specification that documents the key elements of `MyST` syntax that all `preview` / `parsers` should support
2. extension `MyST` specification to document what is available via `Sphinx`
