### ISSUE TITLE
Move our documentation to the sphinx-book-theme

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#54]
How do folks feel about moving our documentation to the [sphinx-book-theme](https://github.com/executablebookproject/sphinx-book-theme)? That way we can dogfood our own tools and become more familiar with them, and hopefully also uncover bugs and think of new features more easily that way.

It will need to wait until pydata cuts a release, so that we can then depend on that release and cut our own pypi release of the book theme.

**Comment by chrisjsewell** [comment]
Sounds good to me, although I just can't take the term dogfood seriously lol

**Comment by chrisjsewell** [comment]
I think all repos are using this theme now 😄
