### ISSUE TITLE
Grab `executablebooks.org`?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#56]
I just noticed that ExecutableBooks.org is available for ~$13 a year. Any interest in using that for documentation instead of `executablebookproject.github.io`?

As an aside, I also grabbed https://github.com/executablebooks just in case we like that name more long-term. I do think it's more memorable than "ExecutableBookProject" but I don't feel strongly about it.

(the reason that I'm bringing this up now is that I realized if we want this org to be a long-term home for our various projects, even beyond the life of the grant, then we should think about memorability and such)

**Comment by chrisjsewell** [comment]
Yeh nice one, I don't think there is any harm in grabbing it 👍

**Comment by choldgraf** [comment]
Cool - I've got the domain now 👍 are folks +1 on me pointing `executablebookproject.github.io` to `executablebooks.org`?

**Comment by jstac** [comment]
Most definitely, nice work @choldgraf

**Comment by choldgraf** [comment]
boom: https://executablebooks.org/en/latest/

**Comment by choldgraf** [comment]
shall I close this? Or should we decide whether we want to rename the github org `executablebooks`as well?

**Comment by jstac** [comment]
Mmmm, I agree with the sentiment but it will break a lot of links and perhaps isn't that important.

It's not unusual to have a URL that's a shortened version of the name of the organization...

**Comment by choldgraf** [comment]
Just a quick note that I don't actually think links will break, they should re-direct to the new org if it is renamed:

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/renaming-an-organization

**Comment by jstac** [comment]
Nice one.  Then I'm indifferent -- please choose if no one weighs in.

**Comment by phaustin** [comment]
One useful first page addition would be prominent pointer to the github repo, now that visitors can't use the github.io address as a clue.

**Comment by choldgraf** [comment]
good point @phaustin - we should update the `meta` docs in general and this could be a part of it.

Want to weigh in on `executablebooks` vs `executablebookproject`? :-)

**Comment by phaustin** [comment]
same information in fewer bits seems like a win to me

**Comment by choldgraf** [comment]
I think my vote would be for `executablebooks` as well since it's easier and shorter to say

**Comment by choldgraf** [comment]
I'll plan to make this switch *tomorrow* unless anybody gives me a thumbs down before then. cc also @mmcky @AakashGfude and @najuzilu who may not have seen this thread

**Comment by choldgraf** [comment]
This is now done - we should update links as we notice
