### ISSUE TITLE
MyST vs myst

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#58]
Three times in the last 2 days now I've had people pronounce MyST as *My ess tee* as opposed to *myst*. I asked about it and they said they thought this is naturally how it was pronounced because of the capitalization.

How do folks feel about this? Are we OK with a lot of people assuming it is *My ess tee*?

And if not, how do we feel about using all-lowercase in our spelling, logos, etc?

**Comment by jstac** [comment]
I like the capitalization `MyST` because it's more recognizable. Could we put "(pronounced 'mist')" in a few places and leave it at that?

**Comment by phaustin** [comment]
Re capitalization -- my carpal tunnel syndrome votes for lower case (kidding).  I do think case consistency between the name and the package import of myst_nb might give new users one less thing to be confused about.

**Comment by phaustin** [comment]
also -- tab completion for macos requires that you know the M is capitalized in order to find MyST.  I was having enough trouble with that that I changed the name of my cloned repo to myst.

**Comment by chrisjsewell** [comment]
I think this shio has sailed now 🚢
