### ISSUE TITLE
Support JOSS with a letter for their Sloan grant

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#59]
Hey all - I spoke recently with Arfon Smith who is one of the leaders of the Journal of Open Source Software (part of "The Open Journals"). We had a productive conversation about Jupyter Book and how it could integrate into some of their publishing pipelines.

JOSS is applying for a grant to Sloan to fund work aimed at generalizing their JOSS publishing infrastructure to be useful to other contexts. It could also potentially work on integrations with open source publishing tools, such as those built by the Executable Books Project.

I've written up a draft letter of support for their application to Sloan. Would others in this team be willing to add their name to the bottom? (comments etc are also welcome!)

https://docs.google.com/document/d/1C_729R5Ws-W8GtNgpYp_V0nP3avZ1laWjIxrWcPbxaE/edit?usp=sharing

If anybody is *not* OK with me giving this letter of support to Arfon to include in their application, please let me know as well. I believe we need to send this to Arfon by **early next week**.

cc @jstac and @gregcaporaso since it'll be particularly helpful to have the other PIs on the grant, but anybody is welcome to add their name if they wish.

**Comment by gregcaporaso** [comment]
Looks good @choldgraf - just reviewed and added my name to the signature.

**Comment by jstac** [comment]
Great letter and I've gladly added my name.

**Comment by thomassargent30** [comment]
Dear Chris,  Hi. I'd be happy to have you add my name if it would help in
any way.
I really like what you have been doing!

Tom Sargent

**Comment by choldgraf** [comment]
@thomassargent30 that would be great, please feel free to add your name to the Google doc link above if you wish! Or should be open to you

**Comment by thomassargent30** [comment]
Dear Chris, I just added my name.

Thanks for taking the lead on this and so many other good things on the
project.

Tom

**Comment by choldgraf** [comment]
Thanks Tom!

A note to all others that I'll plan to send this to Arfon in a couple hours

**Comment by choldgraf** [comment]
thanks all for your help - I sent it to Arfon this evening!
