### ISSUE TITLE
Evaluate potential collaboration and management tools

### ISSUE THREAD

**Issue by mmcky** [executablebooks/meta#6]
There has already been some discussion around possible collaboration tools. 

- [x] `trello` for issue tracking -> **decision:** use github repository for issues, wiki pages etc.
- [x] `zulip` for conversations -> **decision:** won't use an additional tool. most already have slack if needed

It may be nice to evaluate some more project tools for collaborative work on technical specifications and documents:

- [ ] [Confluence](https://www.atlassian.com/software/confluence)

free for small teams (not open source, but open-source license requests are available)

- [ ] [Bookstack](https://www.bookstackapp.com/)

Appears geared towards collaborative document writing, requires self hosting

**Comment by stefanv** [comment]
For collaborative document writing, we've quite enjoyed https://hackmd.io.

**Comment by choldgraf** [comment]
I can't believe I didn't think about hackmd, agreed that's a great way to write in MD

**Comment by jstac** [comment]
I definitely like the look of hackmd.

**Comment by mmcky** [comment]
thanks @stefanv I will take a look. Always great to get recommendations from a user :-)
