### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#62]
Code of Conducts are helpful ways to define the expectations about how people should interact with one another in our public spaces (e.g. github repositories). They are also important for making projects more inclusive and to standardize community norms. How do folks feel about:

1. Adopting a code of conduct for the whole EBP project, that applies to any repository under `executablebooks/`
2. At least as an interrim, say that all EBP repositories need to match the [jupyter code of conduct](https://github.com/jupyter/governance/blob/master/conduct/code_of_conduct.md)

This is something that will be come increasingly important as our repositories start to be used and developed by other people. I don't think it's a crucial thing to have now, but will become moreso over time (if we are successful!)

**Comment by jstac** [comment]
Sounds good to me.  Is there one from Jupyter, say, that we could use off the shelf?

**Comment by choldgraf** [comment]
@jstac yep - see the link in my 2nd point above

**Comment by jstac** [comment]
Sorry @choldgraf, trying to do too many things, gotta read more carefully.

**Comment by chrisjsewell** [comment]
I've added one in executablebooks/.github@af2d9e2b6387413bc9effb25653d6d0748639d10, but feel free to adapt it to be more in line with the jupyter one
