### ISSUE TITLE
Draft of a Jupyter Book rewrite blog post

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#63]
Hey all - I put together the first blog post introducing our new stack. Its goal is to focus on users, give them an idea of what is new in Jupyter Book, and what is different under the hood.

I imagine cross-posting it to the Jupyter Blog, as well as the EBP "updates" section. In the future, I think we could write a follow-up post that dives into the other projects in our stack in more detail.

Would love to hear thoughts, comments, suggestions, and edits (feel free to do so in the hackmd directly):

https://hackmd.io/TAgkZbtiRKmT-4sIGlndaA

**Comment by jstac** [comment]
Great post, nicely written.  Should we thank the Sloan Foundation?

**Comment by rowanc1** [comment]
I also took a read through. Looks super solid, I am sure it will get a good reception!

**Comment by choldgraf** [comment]
great - if nobody objects then when are folks +1 on posting this to the two blogs? I think whenever we are happy to release the v0.7.0 version of jupyter book is a good moment. @jstac just a note there, it will still be in "beta" (it won't be out of beta until jupyter book is 1.0) but it just won't be a "pre-release" anymore, meaning that people will get the new jupyter book just by doing `pip install jupyter-book`.

**Comment by jstac** [comment]
No objections, excited to see more use cases in the wild :-)

Thanks for the explanation.

**Comment by choldgraf** [comment]
Hey all - I'm planning to post this sometime in the next couple of days after we cut another minor release of Jupyter Book. I'll make sure to keep it clear that we are still in beta and things may change / have bugs / etc. I think it'll be good to tell folks about it (and if it doesn't get posted before my kid is born I fear it won't be until like November!). Are folks OK with that?

**Comment by choldgraf** [comment]
I've got a draft PR for an announcement here: https://github.com/executablebooks/meta/pull/91

would love thoughts...and if we can't think of some pre-existing books I think it's OK

**Comment by jstac** [comment]
Looks very nice @choldgraf --- well written and engaging. I suggested optional changes.  Looking forward to seeing this live.

**Comment by chrisjsewell** [comment]
job done 📣
