### ISSUE TITLE
Roadmaps and goals for next phase

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#65]
Hey all - I think that everybody has done a *fantastic* job of getting all of our tools out the door (and in a surprisingly short amount of time!). MyST is generally getting a great reception from the developer community (https://twitter.com/paulweveritt/status/1264181873619730432) and people are really positive about the pre-release for Jupyter Book! 🎉

As more people use the tools, and also potentially become interested in contributing, it'll be helpful for both us and them if we have an idea of where we wanna take things next. What are the directions in which we'd like the project to improve, evolve, etc? What are the major new features, or new bugs, that we'd like to work on?

So this issue is just a place to collect what you all think would be the biggest improvements over what we have right now. Eventually, we can convert this into one-or-more "roadmaps" or "wishlists" that we can use to signal the direction of the project.

I'll try to think about this myself over the next few days, and will add them below! It would be great to see your thoughts as well!

**Comment by thomassargent30** [comment]
Dear Chris and John,

Is it possible to add this Balint Szoke to this stream of messages.
?Together with me, he is doing some testing of the jupyter book machinery
so it would be good for him and
good for us for him to join the community.  Balint's e-mail is:

    balint.szoke@gmail.com

Chris, what you have created is remarkable.  I am very impressed. I am
trying to learn MyST and making some progress!

Tom

**Comment by jstac** [comment]
Hi @thomassargent30, it will be great to have input from Balint.  I'll message him and get him hooked up to the information flow.

**Comment by jstac** [comment]
It would be good to have high quality support for theorems / proofs / definitions / lemmas / etc.  This comment from @najuzilu suggests that we might need to invest some effort:

> I'm currently utilizing sphinxcontrib-proof for the lemmas, theorems, and definitions but I'm not satisfied with the package at all. It's such a headache referencing each element. Unlike figures, which can be easily referenced using {numref}, each lemma and definition can be referenced through {ref} which requires that I go back and forth to check which definition number is being referenced.

**Comment by jstac** [comment]
Multiple themes available off the shelf, similar to Sphinx.  (@DrDrij is working on one for QuantEcon but that's the one thing we'll probably keep private :grimacing: )

**Comment by mmcky** [comment]
> Multiple themes available off the shelf, similar to Sphinx. (@DrDrij is working on one for QuantEcon but that's the one thing we'll probably keep private 😬 )

In addition to the QuantEcon theme work ... @DrDrij will also be working on `minimal`, and `dark` style themes as part of his theme work.

**Comment by mmcky** [comment]
Beyond the improvements needed to develop `LaTeX` further, here are some additional ideas / feature requests for the roadmaps. 

- [ ] improvements to user facing debug support for failing notebooks through `jupyter-cache`. Possible opening notebooks at the point of failure etc. 
- [ ] support in `myst-nb` and `jupyter-cache` for automatic execution testing statistics similar to: https://python.quantecon.org/status.html
- [ ] support for automatic inclusion of [environment information](https://github.com/executablebooks/jupyter-book/issues/517) for `html` and `latex`
- [ ] development of a simple [github action](https://github.com/executablebooks/jupyter-book/issues/510) for automatic deployments of projects hosted on GitHub, and possible integration with `gh-pages`, `s3` hosting

**Future:**

- [ ] community sidebar style chat widget for users `live` browsing pages to chat about content.

**Comment by chrisjsewell** [comment]
Better integration with Jupyter front ends

**Comment by phaustin** [comment]
> Multiple themes available off the shelf, similar to Sphinx. (@DrDrij is working on one for QuantEcon but that's the one thing we'll probably keep private 😬 )

+1 for a simple theme gallery -- we'll be posting  an alpha version of our [pagedown](https://github.com/rstudio/pagedown) theme for myst_nb this week, and having a document that points to examples would be very useful.

**Comment by mmcky** [comment]
Does [VSCode Myst](https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight) support writing `myst` in an `ipynb file that contains `myst` markup?

**Comment by chrisjsewell** [comment]
No not currently I’m afraid. I’m not sure if vscode-python currently offers any extension points for the notebook plugin, whereby we could add such support

**Comment by choldgraf** [comment]
I think much of what I've said has already been described above, but just to re-iterate:

* Better jupyter interfaces support - probably the most common thing people have started raising is wanting their notebooks to behave the same ways in Jupyter interfaces (Lab/Notebook are the most-common but it applies to vscode as well)
* Better cross-language (e.g. R, Julia) support
* Better internationalization and hosted online docs support (e.g. multiple languages in a book)
* More interactivity between markdown and notebook outputs - right now there's still a fairly strong separation between code outputs and markdown, but it would be really cool to incorporate principles of "explorable explanations" and [tangle.js-style content](http://worrydream.com/Tangle/) into Jupyter Book. One promising direction is [Iooxa](https://iooxa.dev/) which has several open source webcomponents for adding this to web pages.

**Comment by chrisjsewell** [comment]
Another point on the roadmap is to update the stack to be compatible with sphinx version 3 (released earlier this year). I didn't want to jump into this straight away, since 3.0.0 seemed to have a lot of bugs, but maybe when 3.1 is released (https://github.com/sphinx-doc/sphinx/milestone/78) it would be a good time to start thinking about this

**Comment by rowanc1** [comment]
Just a sidenote to @choldgraf's point above on [iooxa](http://iooxa.dev/) super excited to be following along with this community and hope that we can help contribute something down the line. What we are creating at the moment is a visual editor for "myst-like" content, and are hoping to support myst natively on our side moving forward.

Currently working on this:
![VisualEditor](https://user-images.githubusercontent.com/913249/84806527-18561680-afc3-11ea-869e-76b31c8b6be8.gif)

Down the line we are envisioning some sort of Jupyter integration to enable users who might not be familiar with the myst syntax (or github) to contribute back to projects easily. I am looking to help out where I can (esp. on pieces that help further explorable explanations!), and will coordinate with @choldgraf.
