### ISSUE TITLE
Add a "team" page to executablebooks.org

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#66]
How do people feel about us adding a team page to executablebooks.org? I imagine that we can use the list of people here:

https://github.com/orgs/executablebooks/people

and programmatically generate a table with EBP members like here: https://jupyterhub-team-compass.readthedocs.io/en/latest/team.html#jupyterhub-team (maybe minus the emojis, unless people would like them)

are folks +1 on that? In general, I'd like to find more ways to surface and recognize the work that the team is doing across these projects, also I'd like a way for us to add new members of the team that weren't a part of the original grant

**Comment by chrisjsewell** [comment]
Sounds good to me

**Comment by jstac** [comment]
Sounds good, thanks @choldgraf .  Switched to public.  CC @mmcky @AakashGfude @najuzilu

**Comment by mmcky** [comment]
thanks @choldgraf -- public now.

**Comment by choldgraf** [comment]
we have a team page! https://executablebooks.org/en/latest/team.html

it'll update each time we build the `meta` docs (so don't build too many times or you'll hit a GitHub API limit)

**Comment by chrisjsewell** [comment]
Thanks 😊 looking good
