### ISSUE TITLE
Show GitHub link/icon in book for reporting errors

### ISSUE THREAD

**Issue by peterennis** [executablebooks/meta#695]
### Describe the problem/need and solution

**Context**
In situations where you're trying to do report a typo or provide a fix

**Problem / Idea**
I had to click through all the listed projects and try to work out where the problem was to be able to make a report.

**Solution**
Provide a GitHub link/icon for page editing or directions on where the project/book source is.

**Benefit**
This would help with simple fixes.

e.g. The reason behind this suggestion is this bug:

https://github.com/executablebooks/sphinx-panels/issues/76

I had to do a lot of searching/reading to find what I think is the right place to report it
and I am still not sure if this is actually the right sub-project.
I was on the verge of giving up because it was such a hassle.

### Guide for implementation

Here is another example of a totally trivial typo that I do not know where else to report:

![trivial typo - Screenshot 2022-03-14 220713](https://user-images.githubusercontent.com/140737/158304488-aaa05109-b5f6-4b7a-a3bb-802b50cb9f9b.png)

and here is a real example of the GitHub link/logo not too far removed from this project:

![Jupyter - Screenshot 2022-03-14 221125](https://user-images.githubusercontent.com/140737/158304951-89cff2a5-8868-4ec1-b883-b02ff369e84a.png)

**Comment by chrisjsewell** [comment]
cc @choldgraf
