### ISSUE TITLE
Upload python3 wheels too

### ISSUE THREAD

**Issue by yuvipanda** [executablebooks/meta#71]
**Is your feature request related to a problem? Please describe.**

I want to be able to install myst-parser from wheels, without having to use the source distribution. However, [pypi](https://pypi.org/project/myst-parser/#files) doesn't have python3 wheels, only python2 wheels.

**Describe the solution you'd like**

The release process includes uploading python3 wheels.

**Describe alternatives you've considered**

Be ok with using source install, since pip does that automatically anyway.

**Additional context**

I was playing with installign this into PyIodide, which seems to [require wheels](https://pyodide.readthedocs.io/en/latest/pypi.html)

**Comment by chrisjsewell** [comment]
moved this to meta since its not a myst-parser issue now

**Comment by chrisjsewell** [comment]
all done
