### ISSUE TITLE
EBP Team Meeting - April

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#710]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: Sydney time at **7:00AM on April 7th** (or the day before depending on your timezone).
- [**Google Calendar Link**](https://calendar.google.com/calendar/embed?src=2nbh00hh9020u622nt0p5qhbek%40group.calendar.google.com&ctz=America%2FLos_Angeles).
- [**Agenda+Video Links**](https://hackmd.io/THymMOAmSICp8rJdB6_Z1w?edit)

If you'd like to discuss something at the meeting, please add an item to the agenda!

### Before the meeting

- [ ] Update dates and make sure HackMD information is correct.
- [ ] Team members add agenda items.
  
### After the meeting

- [ ] Turn any follow-ups into issues/comments/etc.
- [ ] Copy the meeting notes to the docs.
- [ ] Remove notes and clean up HackMD.

**Comment by michaelosthege** [comment]
Hi @choldgraf, are your team meetings open to the community? Or do you have something like "office hours"? (we're experimenting with that in the PyMC project..)
I just saw this a few seconds after I opened yet another [ToC discussion](https://github.com/executablebooks/meta/discussions/715) (I'm sorry!)..

I'd be happy to contribute commits to move article document structures forward, but so far I couldn't even identify an attack surface. I'd be happy about any guidance on that topic.

**Comment by choldgraf** [comment]
@michaelosthege yes these meetings are certainly open to anybody that would like to join! There are no official "office hours" for the project - we have limited resources and time so haven't set up anything like this unfortunately
