### ISSUE TITLE
GitHub Discussions Forum URL not resolving

### ISSUE THREAD

**Issue by matthewfeickert** [executablebooks/meta#717]
:wave: Hi. In PR #614 a link to the GitHub Discussions Forum was added

https://github.com/executablebooks/meta/blob/2d38264ac75ceee8821ff27c7d67be7ac9b92a74/docs/communication.md?plain=1#L8

However, that url `https://discuss.executablebooks.org/` is not resolving (as of today, 2022-04-11). I think(?) it is supposed to redirect to `https://github.com/executablebooks/meta/discussions`, but as I am not sure I thought I would report this instead of opening a PR in the event that this is some momentary issue that can be resolved without code being changed.

**Comment by choldgraf** [comment]
oops - good catch. Wanna open a PR to fix the link?

**Comment by matthewfeickert** [comment]
> oops - good catch. Wanna open a PR to fix the link?

For sure. Do you just want the a direct link to `https://github.com/executablebooks/meta/discussions` or is there another URL that should work for the redirect like you had previously? Or was that just a typo?

**Comment by choldgraf** [comment]
I think you can just link directly to GitHub discussions for now!
