### ISSUE TITLE
Take over stewardship of `thebelab`?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#72]
Hey all - I am curious if folks here are interested in taking over stewardship of the [thebelab project](thebelab.readthedocs.org) (soon to be re-named Thebe). It uses JupyterHub/Binder + JupyterLab APIs and a lightweight Javascript library to convert static websites into dynamic ones where you can run code. We use it in Jupyter Book, and we also have a little Sphinx extension for it here: https://sphinx-thebe.readthedocs.io/en/latest/

Thebelab is currently under @minrk's repository, but we've discussed that it would be better for maintainabiliy / visibility / growth / etc to move it into a community repository somewhere. We've discussed this a bit here: https://github.com/minrk/thebelab/issues/214

The two most-reasonable places seemed to be `jupyterhub/` or `executablebooks/`. I could see an argument for either option, but I'm curious what folks here think about the idea? I think conceptually it could make more sense in `executablebooks/` (since it is primarily about adding interactivity to static pages for improving the reading experience). It should also be a relatively well-scoped project that isn't a *ton* of maintenance burden, as long as we have a basic understanding of javascript workflows.

We're also discussing bringing it into jupyterhub here: https://github.com/jupyterhub/team-compass/issues/313

What do folks think? Of interest?

**Comment by chrisjsewell** [comment]
Yeh if you don't think it will be *too* much of a maintenance burden, I'm happy with that and my JS is pretty decent 😄

**Comment by choldgraf** [comment]
@chrisjsewell I think the JS side shouldn't be too bad. Basically this is what `thebe` does:

* Imports several JupyterLab components to handle the cell execution etc
* Asks Binder/JupyterHub/local jupyter server for a kernel
* Uses the jupyterlab components to communicate w/ that kernel
* Replaces static code elements (e.g., `<pre>`) with interactive ones via `CodeMirror` and hooks it up to the kernel

I think there will be some basic improvements to make (a few feature requests are in the repo, like persisting a Binder session *across* page loads via cookies) but I don't think anything too crazy.

@minrk does that sound right to you? And would you be willing/interested to continue helping with this project if it were in `executablebooks/`? How about @joelachance ?

**Comment by choldgraf** [comment]
@jstac @mmcky @AakashGfude @najuzilu @gregcaporaso I'm also curious what you think - any opinions?

@rowanc1 I would also be curious to hear what you think about this idea! Do you think it makes more sense conceptually in `executablebooks` or `jupyterhub`?

**Comment by AakashGfude** [comment]
@choldgraf my 2 cents. To me, it feels more like an `executablebooks` stack. From the looks of it, it just uses JupyterLab and JupyterHub as a service and does not extend it or inherit it? Also, you mentioned that it can use any of the servers available - Binder, JupyterHub, local server, not necessarily only JupyterHub? 
But it does extend the functionality of `executablebooks`, so can make more sense here?

**Comment by psychemedia** [comment]
As an outside observer, `executablebooks` seems like a more natural home to me than both `jupyterlab` and `jupyterhub` in the sense that it provides a means to consume Jupyter notebook content using Jupyter tools.

**Comment by rowanc1** [comment]
I am also of the opinion that it should be in `executablebooks`, as I think this has the most use as a thin client - and the context of putting it in jupyterhub *conceptually* doesn't fit with that idea to me!
Super excited for this evolution regardless of where it ends up. :)

**Comment by consideRatio** [comment]
I have considered this a while now, and think what matters the most to me is dependency relations. For me with an entrypoint in the z2jh project which install jupyterhub itself, a lot of authenticators, configurable-http-proxy, kubespawner etc, has been my entrypoint to invest time in those other projects. If a release of Kubespawner is made, that influences Z2JH, and it connects the maintainers of these projects.

Currently Thebe is not a dependency for anything in the JupyterHub org. Is it correct that Thebe is a dependency (optional?) for something in the executablebooks org? This is what influences my opinion most.

**Comment by choldgraf** [comment]
@consideRatio currently `Thebe` is only a dependency for one other tool that I know of, which is [`sphinx-thebe`](https://github.com/executablebooks/sphinx-thebe). This is in `executablebooks/` but is also very very young. I don't believe that Thebe has been utilized to its fullest extent so I hope that we see more projects use it. However my intuition is that it's more likely those projects would be in `executablebooks/` than `jupyterhub/`. What do you think?

**Comment by consideRatio** [comment]
> However my intuition is that it's more likely those projects would be in executablebooks/ than jupyterhub/. What do you think?

I'm +1 for adoption by executablebooks since I think it will interconnect in this org.

**Comment by minrk** [comment]
@choldgraf great description! And yes, I'll definitely continue to help out wherever it lands. Indeed, most of the skills involved in maintaining it should be pretty general web frontend stuff: manipulating elements on a page, persisting state in a browser, etc.. The two APIs it consumes that may require some reading for certain kinds of tasks are the binderhub build/launch API and the jupyterlab APIs for running code / displaying output.

I also agree that executable books is a logical home for thebe *in terms of mission*: facilitate adding execution to things published on the web; even if there are not many technical connections just yet, so happy to see folks receptive to it.

**Comment by joelachance** [comment]
Happy to continue helping wherever Thebe lands!

**Comment by choldgraf** [comment]
So, somebody correct me if I'm wrong, but I am sensing an in-general higher amount of enthusiasm for putting this in `executablebooks/` than `jupyterhub/` from a "conceptual overlap" standpoint. I think this is reasonable as well. Shall we decide on `executablebooks/thebe` then? (I guess `thebelab/` but this also seems like a good time to make the name switch too)
