### ISSUE TITLE
[short notice] Give a talk at JupyterCon

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#73]
This is **very very short notice** - so I apologize for not catching it sooner - but the JupyterCon 2020 CFP for talks closes Monday night (Pacific time). I think that we could use this conference as an opportunity to give a talk about the ExecutableBooks project, the new Jupyter Book re-write, etc.

I am happy to submit a proposal on our behalf. I think that if we frame it as a "next evolution of Jupyter Book" kinda thing, then it'll have a very high probability of being accepted (I'd probably submit it under the "Jupyter Tools" track).

I've started off with a very rough title/outline at this doc link:

https://docs.google.com/document/d/1S-piiM9gjqq886BKEGKzKdXRJBuEMC6EGEFhnvAaPkQ/edit?usp=sharing

I'd love any comments, edits, suggestions etc, as well as a signal as to whether you think this is or isn't a good idea! If I don't hear any strong negative responses I'll plan to submit the application in ~36 hours (Monday evening California time)

Let me know what you all think!

**Comment by jstac** [comment]
Sound good @choldgraf , thanks for putting it together.  I like your outline.

I suppose the other thing to do is point people towards examples in the wild.  Do you have a list?  Here's the link to the Japanese one again: https://py4etrics.github.io/, https://py4etrics.github.io/part_2.html

**Comment by rowanc1** [comment]
I think it is a really good idea. :)

**Comment by chrisjsewell** [comment]
sounds good to me 👍 (I added a few notes)

> examples in the wild. Do you have a list?

there is also always https://github.com/executablebooks/jupyter-book/network/dependents (+ https://github.com/executablebooks/MyST-Parser/network/dependents)

**Comment by chrisjsewell** [comment]
> https://github.com/executablebooks/MyST-Parser/network/dependents?package_id=UGFja2FnZS05NjQ5Njg1NTY%3D

Nice to see there are some "big" players starting to use MyST: jupyterhub, google, nteract, ansible

**Comment by chrisjsewell** [comment]
> https://github.com/executablebooks/jupyter-book/network/dependents 

The big (most stars) examples are:

- https://github.com/microsoft/tigertoolbox
- https://github.com/stanfordmlgroup/ngboost
- https://github.com/Cyb3rWard0g/HELK
- https://github.com/hunters-forge/mordor
- https://github.com/data-8/textbook
- https://github.com/altair-viz/altair-tutorial
- https://github.com/qiskit-community/qiskit-textbook

**Comment by choldgraf** [comment]
> Nice to see there are some "big" players starting to use MyST: jupyterhub, google, nteract, ansible

Anecdotally, I think that folks are generally _really_ excited about MyST. I've heard a lot of great things about it. We should definitely highlight it as a standalone tool as a part of this talk :-)

**Comment by choldgraf** [comment]
> Thank you for submitting your proposal "The new Jupyter Book - beautiful, interactive, publication-quality books built with Jupyter" to JupyterCon 2020. In order to hear from more speakers, we are introducing a new 12-minute talk option. We are pleased to inform you that your Jupyter Community: Tools and Practices Talk "The new Jupyter Book - beautiful, interactive, publication-quality books built with Jupyter" has been selected for a 12-minute talk. We’re looking forward to an incredible event!

> If you would like to instead present your topic as a poster in our poster session, we would be happy to accept your proposal as a poster submission instead. Posters consist of a 2-minute prerecorded video overview, a poster pdf file and thumbnail for the gallery, and a description that can include a link to an interactive site such as a Voila dashboard. See the Posters at JupyterCon 2020 section on the JupyterCon website for more information.

> Please reply to this email by Wednesday, August 19, to confirm whether you are still available to present your Jupyter Community: Tools and Practices Talk "The new Jupyter Book - beautiful, interactive, publication-quality books built with Jupyter" as a 12-minute talk (or let us know if you would rather convert it to a poster).

> As you know, JupyterCon 2020 is an online conference. Your talk will be prerecorded and broadcast during the conference. Your video will need to be uploaded to our system by Friday, September 11. Your talk video should be at most 12 minutes long. We will send you additional information next week, including how to upload your video and other helpful tips for recording your video. In the meantime, please let us know if you have any questions by contacting us at jupytercon-techprog@numfocus.org.

> For your information, we have enclosed below the comments from reviewers for your proposal.

**Comment by chrisjsewell** [comment]
Aslo note myst-parser is a dependency in the official jupytercon tutorial template 😄  https://github.com/jupytercon/tutorial2020/blob/f33ebcfb93a0333f71f0b3a5f39a00fe5a56c4a9/requirements.txt#L3
(I made a PR for them to update the version! https://github.com/jupytercon/tutorial2020/pull/4)
