### ISSUE TITLE
Plan for Chris' upcoming baby leave

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#76]
Hey all - I think I've told you all, but just to make sure: I'm expecting a baby girl (our first) in early August! (if this is the first you've heard of this...then surprise!!!!)

## What to expect

I plan on taking roughly 1-2 months of "Chris is totally unreliable". Maybe more, maybe less depending on how we are doing, but this is what we should plan on. I'll be *very rarely* checking emails etc so I can jump in if there's an emergency, but day-to-day duties I probably shouldn't be relied on for anything.

I think that the current status of the Executable Books stack is in good shape. Our lower-level repositories have started to solidify nicely and we've had fewer and fewer major changes, which is a good thing. Folks seem to really like MyST markdown, which is awesome. They're also intrigued by MyST Notebooks, though I detect some confusion as to how "MyST-NB" (the sphinx package) and "MyST Notebooks" (the notebook format) relate to each other. Jupyter Book has also seen a few big-ish API changes, but hopefully those will solidify over time as well.

## Some things others could keep watch over for a bit

Here are a few things that I want to highlight that others may wish to spend time on / think about in my absence:

* We have an ongoing conversation with Eric from ReadTheDocs about getting **Jupyter Book in readthedocs** and/or MyST markdown adopted as an "official" recommendation from RTD.
* We still need to **"announce" a new Jupyter Book** (we've made a few releases, but no big splash yet). I think it'd be good to do this *before* JupyterCon so that we can use the conference to build more momentum.
* I'm going to submit a **JupyterCon talk for October**. I think this has a high chance of being accepted. I'm happy to put in the time to give the presentation (it is pre-recorded so timing is hopefully not as much of an issue) but would love assistance here or in the subsequent Q&A sessions).
* **Jupyter Book and sphinx-book-theme could use more 👀 on it** to help with issue triage, merges, etc. As more people are using it, more and more issues are being created and I'm not able to keep up right now, much less when I'm on leave. If you want a little dashboardy idea of what's happening across our repos, [check out this `executablebooks` dashboard page](https://predictablynoisy.com/jupyter-activity-snapshot/executablebooks.html)
* We have a potential **collaboration with [Iooxa](https://iooxa.dev)** brewing that I want to make sure we don't drop, as this could result in some interesting new developments on the web/javascript/authoring side of things. It's something we could potentially use some of the Berkeley grant $$ on.

Not all of these need to be equally prioritized, but I wanted to put it all out here for transparency's sake and so we can get an idea of what to focus on.

## Things I hope to get done before I go on leave

* Merge some of the outstanding PRs in jupyter book, sphinx-book-theme, etc
* Get another minor release of Jupyter Book out (`7.2`)
* Submit jupytercon talk
* Anything else???

Lemme know if you have any thoughts / comments / or questions. I'd also be happy to have a meeting to re-sync with folks (either as a group or via 1-on-1s) in the next week or two.

**Comment by mmcky** [comment]
thanks for putting this issue together @choldgraf -- it would be great to link up with you in the next week or so. I will try and step up and be more active in discussions in August to keep some things moving forward. One thing would be great is to get a high level run down of key stakeholders that have been making contributions etc.

**Comment by chrisjsewell** [comment]
Tssk, how selfish 😆 But yeh, hope preparations are going well!
Happy to jump in on a zoom whenever peeps are available

**Comment by chrisjsewell** [comment]
> We have an ongoing conversation with Eric from ReadTheDocs about getting Jupyter Book in readthedocs and/or MyST markdown adopted as an "official" recommendation from RTD.

@choldgraf when you return I definitely want to push this forward.
I think that myst-parser is now in good shape to "fully replace" RecommonMark (particularly with the recent addition of the `eval-rst` special directive)

At some point I, maybe after this is resolved, I want to make a PR to sphinx, to reference myst-parser in https://www.sphinx-doc.org/en/master/usage/markdown.html, and post a message to the docutils/sphinx mailing lists to promote it (as a ~drop in replacement).
