### ISSUE TITLE
Add to developer conventions (issue labels, PR prfixes)

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/meta#78]
As mentioned in https://github.com/executablebooks/jupyter-book/blob/master/docs/contribute/intro.md,
then probably this text can be removed from that page and a link added to here

**Comment by chrisjsewell** [comment]
Note also https://github.com/organizations/executablebooks/settings/repository-defaults could be reviewed to update defintions and add/remove any extra labels

**Comment by choldgraf** [comment]
@chrisjsewell do you think this is now addressed with your latest improvements to the website?

**Comment by chrisjsewell** [comment]
No, I think it shouldn't be closed until these filesn/sections have been removed/altered from jupyter-book:

- https://github.com/executablebooks/jupyter-book/blob/master/docs/contribute/intro.md
- https://github.com/executablebooks/jupyter-book/blob/master/docs/contribute/develop.md
- https://github.com/executablebooks/jupyter-book/blob/master/RELEASES.md
- https://github.com/executablebooks/jupyter-book/blob/master/MAINTAINING.md
- https://github.com/executablebooks/jupyter-book/blob/master/CODE_OF_CONDUCT.md
- https://github.com/executablebooks/jupyter-book/blob/master/CONTRIBUTING.md
- https://github.com/executablebooks/jupyter-book/blob/master/README.md#contribute-or-improve-the-book

Most of this should be "deprecated" in favour of files/sections in https://github.com/executablebooks/.github; either completely removing them or referencing them and only keeping any information that is specific to jupyter-book

For example, a nitpick 😬, in 5cc8ea10affde659e708fc3944ff5df51bb8bdbe, you *almost* followed [CONTRIBUTING.md#releases-and-change-log](https://github.com/executablebooks/.github/blob/master/CONTRIBUTING.md#releases-and-change-logs) lol, but `RELEASES.md` is still not strictly equal to it, since (a) `github-activity` does not yet create a changelog with matching sub-headings (there is also no link of how to install it) and (b) you didn't update https://github.com/executablebooks/jupyter-book/blob/master/CHANGELOG.md, which is only populated up to version 6.2

**Comment by chrisjsewell** [comment]
Another nit pick; in the last few commits you've used `📚 DOC`, `📖 DOC`, `📚 DOCS`, `📖 DOCS`, just pick one! 😆 
(Maybe the 📚 does look nicer, also `✏️ REWRITE` is for typos and minor changes)

**Comment by choldgraf** [comment]
I'm fine doing all those deprecations, I was imagining opening an issue in jupyter book to track the changes in that repo, but we can leave it to this issue if you wish

for the emojis, that's because my computer's emoji thing and the github emoji thing are switched :-( in github `book` is 📖 
while on my computer it is 📚 so it depends which interface I'm using to type the emoji. I will try to be more consistent (though I agree that 📚 is easier to distinguish from the others, 📖 just kinda looks like a white rectangle to me)

**Comment by chrisjsewell** [comment]
> that's because my computer's emoji thing and the github emoji thing are switched

haha thats annoying

> 📖 just kinda looks like a white rectangle to me

yep changed in executablebooks/.github@89fe8e398f5f14ea4e9796189ce418741f271b39

openeded the issue in jupyter-books so closing this
