### ISSUE TITLE
Can anybody else lead team meetings?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#795]
As folks have probably noticed, we haven't had a team meeting in a few months. Between moving to France and things ramping up more with my job @ 2i2c, I don't have time to manage and oversee the team meetings for this project anymore.

Is anybody interested in coordinating and leading the team meetings for the EBP? I believe that @rowanc1 mentioned he might be interested in this so pinging him for visibility.

**Comment by rowanc1** [comment]
Yes, I would be up for helping out here and getting back into these in September.

Does the previous time work at least for the first one back?
https://executablebooks.org/en/latest/meetings/index.html#team-calendar

@choldgraf do you have access to the calendar to update the descriptions at least?

**Comment by choldgraf** [comment]
@rowanc1 I've just shared the calendar maintainer permissions with you (both your gmail and curvenote address), feel free to share with others as well!

**Comment by mmcky** [comment]
thanks @rowanc1 

My schedule will allow me to kick in again from September also. @rowanc1 do you think we should adopt a dual timezone month-on-month-off meeting to capture Canada/Europe and Canada/Australia pairs. If so, it would seem to make sense to pivot around Canada/US?

**Comment by chrisjsewell** [comment]
Heya, if I'm reading correctly, then the next meeting is scheduled for Wednesday 31st 11pm CEST. I maybe won't be able to attend this, since I'll be going to https://www.euroscipy.org/2022/social_event.html, until 2030. I guess it depends what happens after 😄

**Comment by choldgraf** [comment]
@chrisjsewell I'll actually be there as well (for one night, arriving Wed and leaving Thurs), see you there!

**Comment by chrisjsewell** [comment]
> @chrisjsewell I'll actually be there as well (for one night, arriving Wed and leaving Thurs), see you there!

Indeed, I was thinking you might be 😄 yep same for me, just wed & thur 👍 
Was thinking to give a lightening talk on jupyter-book actually, maybe do a bit of improvements of https://executablebooks.org/en/latest/gallery.html before (to make things a bit more searchable) and advertise people adding their projects to it

**Comment by rowanc1** [comment]
I have updated the meeting notes, tested out the links, and updated the calendar invite! I put an agenda on to talk about some of the updates in the JS ecosystem that touch on docs, latex, etc.

Notes will be here:
https://hackmd.io/@rowanc1/rJOI5qIys

Looking forward to seeing anyone who can make it!

**Comment by rowanc1** [comment]
Thanks for everyone who came today! Had a good discussion on a wide variety of things.

* I showed some updates on mystjs side ([slides](https://docs.google.com/presentation/d/1ZopCDDL4F1HkL-0z4NCn0IGNmgj8s3ISOC0ZN7XZgVM/edit), [twitter thread](https://twitter.com/rowancockett/status/1562133043296382976))
* Top challenge: Getting JupyterBook to the next version of the myst-parser, and upgrading sphinx-jupyterbook-latex to be compatible with recent changes.
* Upcoming: more convo on the `myst-spec` implementation, and how that fits in with JupyterBook updates

Had fun showing off some new features of cross-referencing in mystjs for the docs on the myst-spec (cc @tonyfast):
![spec-recursion](https://user-images.githubusercontent.com/913249/187799640-7da3a96f-7687-49a9-b263-079d775cbaa1.gif)

@choldgraf is best practice to get the cleaned up meeting notes into this repository and published?

**Comment by mmcky** [comment]
Thanks @rowanc1 for hosting. It was super fun to catch up with everyone and to see the massive progress made on `mystjs`.

**Comment by rowanc1** [comment]
Closing this issue, I am happy to help out facilitating these meetings for the foreseeable future! Looking forward to the meeting this month: #831
