### ISSUE TITLE
EBP Team Meeting - November 2022

### ISSUE THREAD

**Issue by mmcky** [executablebooks/meta#865]
Hello @executablebooks/ebpteam! This is an issue to track the next Executable Books team meeting! Here's some relevant information:

- **Date**: Sydney time at **7:00AM on 03rd November 2022** (or the day before depending on your timezone).
- [**Google Calendar Link**](https://calendar.google.com/calendar/embed?src=2nbh00hh9020u622nt0p5qhbek%40group.calendar.google.com&ctz=America%2FLos_Angeles).
- [**Agenda+Video Links**](https://hackmd.io/@rKTqyMEmTBW7EDG4_LXfvA/HJWtMYyro)

If you'd like to discuss something at the meeting, please add an item to the agenda!

### Before the meeting

- [x] Update dates and make sure HackMD information is correct.
- [ ] Team members add agenda items.
  
### After the meeting

- [ ] Turn any follow-ups into issues/comments/etc.
- [ ] Copy the meeting notes to the docs.
- [ ] Remove notes and clean up HackMD.

**Comment by mmcky** [comment]
@fwkoch did you add those links to the HackMD linked by this issue?

**Comment by fwkoch** [comment]
Thanks! I was in a hackmd from the meeting invite... now I know to trust this one instead!
