### ISSUE TITLE
[blog post] MyST JS and specification progress

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/meta#923]
Over the last year there has been a lot of new development in the myst side of the executable books project. In particular, we have a JavaScript implementation of the MyST parser, and work from the curvenote team to bring in their document engine into MyST JS. That's a current WIP, [hosted at js.myst.tools](https://js.myst.tools/).

We should write a blog post that describes our plans to explore JavaScript implementations of the MyST parser/document system, integrations with Jupyter, the specification to standardize syntax between implementations, and moving this as a parallel effort alongside the Python stack.

### Related issues

- https://github.com/executablebooks/meta/issues/838
- https://github.com/executablebooks/meta/issues/793
- https://github.com/executablebooks/meta/issues/538
- https://github.com/executablebooks/meta/issues/118

**Comment by rowanc1** [comment]
There is also a draft of a blog post here:

- https://github.com/executablebooks/meta/pull/723

I think parts of it (e.g. the overview) are pretty good, some of the details would need to be updated. Perhaps there is some content in there that you can pull from, and can follow this up soon with some more details!

**Comment by stevejpurves** [comment]
This issue can now be closed? as it relates to this post https://executablebooks.org/en/latest/blog/2023/announce-mystjs/ ?

**Comment by choldgraf** [comment]
Yes! Good catch.

Closed by https://github.com/executablebooks/meta/pull/936
