### ISSUE TITLE
"Time to read" page element

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/meta#96]
As per the jupyter blog, it would be nice to have a way to insert approximate read times for certain pages:

![image](https://user-images.githubusercontent.com/2997570/90070606-0dcaab80-dcec-11ea-8f57-fc61737cc48c.png)

**Comment by chrisjsewell** [comment]
I guess you could either do it "post-processed" with a HTML/JS script like https://github.com/michael-lynch/reading-time, or "bottom-up" counting the words in the markdown-it-py parsed tokens.

**Comment by choldgraf** [comment]
I think this now exists via https://myst-parser.readthedocs.io/en/latest/develop/_changelog.html?highlight=sub-ref#new-features so closing this
