### ISSUE TITLE
sphinx-tabs maybe unmaintained

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/meta#98]
sphinx-tabs appears unmaintained (https://github.com/djungelorm/sphinx-tabs/issues/67), or at least the developer is very inactive (see https://github.com/djungelorm).

Already, we get lots of pytest warnings in jupyter-book due to this outstanding PR https://github.com/djungelorm/sphinx-tabs/pull/59.

In https://github.com/djungelorm/sphinx-tabs/issues/67 I have asked about moving it to EBP, so will see if there is any reply then re-assess

also cc @pradyunsg

**Comment by choldgraf** [comment]
or we just https://github.com/executablebooks/sphinx-panels/issues/28

;-)

**Comment by pradyunsg** [comment]
> will see if there is any reply then re-assess

Sounds good to me! In case we don't get a response, PEP 541 exists!

**Comment by chrisjsewell** [comment]
done and dusted https://github.com/executablebooks/sphinx-tabs/blob/master/CHANGELOG.md

**Comment by choldgraf** [comment]
Perhaps we should confirm once we've been able to make the first pypi release?

**Comment by chrisjsewell** [comment]
Already done 🕺

**Comment by chrisjsewell** [comment]
https://pypi.org/project/sphinx-tabs/
